// Mocks generated by Mockito 5.4.6 from annotations
// in travel_crew/test/features/itinerary/domain/usecases/update_itinerary_item_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:travel_crew/features/itinerary/domain/repositories/itinerary_repository.dart'
    as _i3;
import 'package:travel_crew/shared/models/itinerary_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeItineraryItemModel_0 extends _i1.SmartFake
    implements _i2.ItineraryItemModel {
  _FakeItineraryItemModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ItineraryRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockItineraryRepository extends _i1.Mock
    implements _i3.ItineraryRepository {
  MockItineraryRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ItineraryItemModel> createItineraryItem({
    required String? tripId,
    required String? title,
    String? description,
    String? location,
    double? latitude,
    double? longitude,
    String? placeId,
    DateTime? startTime,
    DateTime? endTime,
    int? dayNumber,
    int? orderIndex = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createItineraryItem, [], {
              #tripId: tripId,
              #title: title,
              #description: description,
              #location: location,
              #latitude: latitude,
              #longitude: longitude,
              #placeId: placeId,
              #startTime: startTime,
              #endTime: endTime,
              #dayNumber: dayNumber,
              #orderIndex: orderIndex,
            }),
            returnValue: _i4.Future<_i2.ItineraryItemModel>.value(
              _FakeItineraryItemModel_0(
                this,
                Invocation.method(#createItineraryItem, [], {
                  #tripId: tripId,
                  #title: title,
                  #description: description,
                  #location: location,
                  #latitude: latitude,
                  #longitude: longitude,
                  #placeId: placeId,
                  #startTime: startTime,
                  #endTime: endTime,
                  #dayNumber: dayNumber,
                  #orderIndex: orderIndex,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ItineraryItemModel>);

  @override
  _i4.Future<List<_i2.ItineraryItemModel>> getTripItinerary(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#getTripItinerary, [tripId]),
            returnValue: _i4.Future<List<_i2.ItineraryItemModel>>.value(
              <_i2.ItineraryItemModel>[],
            ),
          )
          as _i4.Future<List<_i2.ItineraryItemModel>>);

  @override
  _i4.Future<List<_i2.ItineraryItemModel>> getDayItinerary({
    required String? tripId,
    required int? dayNumber,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDayItinerary, [], {
              #tripId: tripId,
              #dayNumber: dayNumber,
            }),
            returnValue: _i4.Future<List<_i2.ItineraryItemModel>>.value(
              <_i2.ItineraryItemModel>[],
            ),
          )
          as _i4.Future<List<_i2.ItineraryItemModel>>);

  @override
  _i4.Future<List<_i2.ItineraryDay>> getItineraryByDays(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#getItineraryByDays, [tripId]),
            returnValue: _i4.Future<List<_i2.ItineraryDay>>.value(
              <_i2.ItineraryDay>[],
            ),
          )
          as _i4.Future<List<_i2.ItineraryDay>>);

  @override
  _i4.Future<_i2.ItineraryItemModel> getItineraryItem(String? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#getItineraryItem, [itemId]),
            returnValue: _i4.Future<_i2.ItineraryItemModel>.value(
              _FakeItineraryItemModel_0(
                this,
                Invocation.method(#getItineraryItem, [itemId]),
              ),
            ),
          )
          as _i4.Future<_i2.ItineraryItemModel>);

  @override
  _i4.Future<_i2.ItineraryItemModel> updateItineraryItem({
    required String? itemId,
    String? title,
    String? description,
    String? location,
    double? latitude,
    double? longitude,
    String? placeId,
    DateTime? startTime,
    DateTime? endTime,
    int? dayNumber,
    int? orderIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateItineraryItem, [], {
              #itemId: itemId,
              #title: title,
              #description: description,
              #location: location,
              #latitude: latitude,
              #longitude: longitude,
              #placeId: placeId,
              #startTime: startTime,
              #endTime: endTime,
              #dayNumber: dayNumber,
              #orderIndex: orderIndex,
            }),
            returnValue: _i4.Future<_i2.ItineraryItemModel>.value(
              _FakeItineraryItemModel_0(
                this,
                Invocation.method(#updateItineraryItem, [], {
                  #itemId: itemId,
                  #title: title,
                  #description: description,
                  #location: location,
                  #latitude: latitude,
                  #longitude: longitude,
                  #placeId: placeId,
                  #startTime: startTime,
                  #endTime: endTime,
                  #dayNumber: dayNumber,
                  #orderIndex: orderIndex,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ItineraryItemModel>);

  @override
  _i4.Future<void> deleteItineraryItem(String? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteItineraryItem, [itemId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> reorderItems({
    required String? tripId,
    required int? dayNumber,
    required List<String>? itemIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reorderItems, [], {
              #tripId: tripId,
              #dayNumber: dayNumber,
              #itemIds: itemIds,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> moveItemToDay({
    required String? itemId,
    required int? newDayNumber,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#moveItemToDay, [], {
              #itemId: itemId,
              #newDayNumber: newDayNumber,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<_i2.ItineraryItemModel>> watchTripItinerary(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#watchTripItinerary, [tripId]),
            returnValue: _i4.Stream<List<_i2.ItineraryItemModel>>.empty(),
          )
          as _i4.Stream<List<_i2.ItineraryItemModel>>);

  @override
  _i4.Stream<List<_i2.ItineraryDay>> watchItineraryByDays(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#watchItineraryByDays, [tripId]),
            returnValue: _i4.Stream<List<_i2.ItineraryDay>>.empty(),
          )
          as _i4.Stream<List<_i2.ItineraryDay>>);
}
