// Mocks generated by Mockito 5.4.6 from annotations
// in travel_crew/test/features/emergency/integration/medical_emergency_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:geolocator/geolocator.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:travel_crew/core/services/location_service.dart' as _i9;
import 'package:travel_crew/features/emergency/data/datasources/emergency_remote_datasource.dart'
    as _i6;
import 'package:travel_crew/shared/models/emergency_alert_model.dart' as _i4;
import 'package:travel_crew/shared/models/emergency_contact_model.dart' as _i2;
import 'package:travel_crew/shared/models/hospital_model.dart' as _i8;
import 'package:travel_crew/shared/models/location_share_model.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEmergencyContactModel_0 extends _i1.SmartFake
    implements _i2.EmergencyContactModel {
  _FakeEmergencyContactModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLocationShareModel_1 extends _i1.SmartFake
    implements _i3.LocationShareModel {
  _FakeLocationShareModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEmergencyAlertModel_2 extends _i1.SmartFake
    implements _i4.EmergencyAlertModel {
  _FakeEmergencyAlertModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePosition_3 extends _i1.SmartFake implements _i5.Position {
  _FakePosition_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [EmergencyRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockEmergencyRemoteDataSource extends _i1.Mock
    implements _i6.EmergencyRemoteDataSource {
  MockEmergencyRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i2.EmergencyContactModel>> getEmergencyContacts() =>
      (super.noSuchMethod(
            Invocation.method(#getEmergencyContacts, []),
            returnValue: _i7.Future<List<_i2.EmergencyContactModel>>.value(
              <_i2.EmergencyContactModel>[],
            ),
          )
          as _i7.Future<List<_i2.EmergencyContactModel>>);

  @override
  _i7.Future<_i2.EmergencyContactModel?> getEmergencyContactById(
    String? contactId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getEmergencyContactById, [contactId]),
            returnValue: _i7.Future<_i2.EmergencyContactModel?>.value(),
          )
          as _i7.Future<_i2.EmergencyContactModel?>);

  @override
  _i7.Future<_i2.EmergencyContactModel> addEmergencyContact({
    required String? name,
    required String? phoneNumber,
    String? email,
    required String? relationship,
    bool? isPrimary = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addEmergencyContact, [], {
              #name: name,
              #phoneNumber: phoneNumber,
              #email: email,
              #relationship: relationship,
              #isPrimary: isPrimary,
            }),
            returnValue: _i7.Future<_i2.EmergencyContactModel>.value(
              _FakeEmergencyContactModel_0(
                this,
                Invocation.method(#addEmergencyContact, [], {
                  #name: name,
                  #phoneNumber: phoneNumber,
                  #email: email,
                  #relationship: relationship,
                  #isPrimary: isPrimary,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.EmergencyContactModel>);

  @override
  _i7.Future<_i2.EmergencyContactModel> updateEmergencyContact({
    required String? contactId,
    String? name,
    String? phoneNumber,
    String? email,
    String? relationship,
    bool? isPrimary,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateEmergencyContact, [], {
              #contactId: contactId,
              #name: name,
              #phoneNumber: phoneNumber,
              #email: email,
              #relationship: relationship,
              #isPrimary: isPrimary,
            }),
            returnValue: _i7.Future<_i2.EmergencyContactModel>.value(
              _FakeEmergencyContactModel_0(
                this,
                Invocation.method(#updateEmergencyContact, [], {
                  #contactId: contactId,
                  #name: name,
                  #phoneNumber: phoneNumber,
                  #email: email,
                  #relationship: relationship,
                  #isPrimary: isPrimary,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.EmergencyContactModel>);

  @override
  _i7.Future<void> deleteEmergencyContact(String? contactId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteEmergencyContact, [contactId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> setPrimaryContact(String? contactId) =>
      (super.noSuchMethod(
            Invocation.method(#setPrimaryContact, [contactId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i3.LocationShareModel> startLocationSharing({
    required List<String>? contactIds,
    String? tripId,
    Duration? duration,
    String? message,
    required double? latitude,
    required double? longitude,
    double? accuracy,
    double? altitude,
    double? speed,
    double? heading,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startLocationSharing, [], {
              #contactIds: contactIds,
              #tripId: tripId,
              #duration: duration,
              #message: message,
              #latitude: latitude,
              #longitude: longitude,
              #accuracy: accuracy,
              #altitude: altitude,
              #speed: speed,
              #heading: heading,
            }),
            returnValue: _i7.Future<_i3.LocationShareModel>.value(
              _FakeLocationShareModel_1(
                this,
                Invocation.method(#startLocationSharing, [], {
                  #contactIds: contactIds,
                  #tripId: tripId,
                  #duration: duration,
                  #message: message,
                  #latitude: latitude,
                  #longitude: longitude,
                  #accuracy: accuracy,
                  #altitude: altitude,
                  #speed: speed,
                  #heading: heading,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.LocationShareModel>);

  @override
  _i7.Future<_i3.LocationShareModel> updateSharedLocation({
    required String? sessionId,
    required double? latitude,
    required double? longitude,
    double? accuracy,
    double? altitude,
    double? speed,
    double? heading,
    String? message,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateSharedLocation, [], {
              #sessionId: sessionId,
              #latitude: latitude,
              #longitude: longitude,
              #accuracy: accuracy,
              #altitude: altitude,
              #speed: speed,
              #heading: heading,
              #message: message,
            }),
            returnValue: _i7.Future<_i3.LocationShareModel>.value(
              _FakeLocationShareModel_1(
                this,
                Invocation.method(#updateSharedLocation, [], {
                  #sessionId: sessionId,
                  #latitude: latitude,
                  #longitude: longitude,
                  #accuracy: accuracy,
                  #altitude: altitude,
                  #speed: speed,
                  #heading: heading,
                  #message: message,
                }),
              ),
            ),
          )
          as _i7.Future<_i3.LocationShareModel>);

  @override
  _i7.Future<void> pauseLocationSharing(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#pauseLocationSharing, [sessionId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> resumeLocationSharing(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#resumeLocationSharing, [sessionId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> stopLocationSharing(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#stopLocationSharing, [sessionId]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i3.LocationShareModel?> getActiveLocationShare() =>
      (super.noSuchMethod(
            Invocation.method(#getActiveLocationShare, []),
            returnValue: _i7.Future<_i3.LocationShareModel?>.value(),
          )
          as _i7.Future<_i3.LocationShareModel?>);

  @override
  _i7.Stream<_i3.LocationShareModel> watchLocationShare(String? sessionId) =>
      (super.noSuchMethod(
            Invocation.method(#watchLocationShare, [sessionId]),
            returnValue: _i7.Stream<_i3.LocationShareModel>.empty(),
          )
          as _i7.Stream<_i3.LocationShareModel>);

  @override
  _i7.Future<List<_i3.LocationShareModel>> getSharedLocations() =>
      (super.noSuchMethod(
            Invocation.method(#getSharedLocations, []),
            returnValue: _i7.Future<List<_i3.LocationShareModel>>.value(
              <_i3.LocationShareModel>[],
            ),
          )
          as _i7.Future<List<_i3.LocationShareModel>>);

  @override
  _i7.Future<_i4.EmergencyAlertModel> triggerEmergencyAlert({
    required _i4.EmergencyAlertType? type,
    String? tripId,
    String? message,
    double? latitude,
    double? longitude,
    List<String>? contactIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#triggerEmergencyAlert, [], {
              #type: type,
              #tripId: tripId,
              #message: message,
              #latitude: latitude,
              #longitude: longitude,
              #contactIds: contactIds,
            }),
            returnValue: _i7.Future<_i4.EmergencyAlertModel>.value(
              _FakeEmergencyAlertModel_2(
                this,
                Invocation.method(#triggerEmergencyAlert, [], {
                  #type: type,
                  #tripId: tripId,
                  #message: message,
                  #latitude: latitude,
                  #longitude: longitude,
                  #contactIds: contactIds,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.EmergencyAlertModel>);

  @override
  _i7.Future<_i4.EmergencyAlertModel> acknowledgeAlert(String? alertId) =>
      (super.noSuchMethod(
            Invocation.method(#acknowledgeAlert, [alertId]),
            returnValue: _i7.Future<_i4.EmergencyAlertModel>.value(
              _FakeEmergencyAlertModel_2(
                this,
                Invocation.method(#acknowledgeAlert, [alertId]),
              ),
            ),
          )
          as _i7.Future<_i4.EmergencyAlertModel>);

  @override
  _i7.Future<_i4.EmergencyAlertModel> resolveAlert({
    required String? alertId,
    String? resolution,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#resolveAlert, [], {
              #alertId: alertId,
              #resolution: resolution,
            }),
            returnValue: _i7.Future<_i4.EmergencyAlertModel>.value(
              _FakeEmergencyAlertModel_2(
                this,
                Invocation.method(#resolveAlert, [], {
                  #alertId: alertId,
                  #resolution: resolution,
                }),
              ),
            ),
          )
          as _i7.Future<_i4.EmergencyAlertModel>);

  @override
  _i7.Future<_i4.EmergencyAlertModel> cancelAlert(String? alertId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelAlert, [alertId]),
            returnValue: _i7.Future<_i4.EmergencyAlertModel>.value(
              _FakeEmergencyAlertModel_2(
                this,
                Invocation.method(#cancelAlert, [alertId]),
              ),
            ),
          )
          as _i7.Future<_i4.EmergencyAlertModel>);

  @override
  _i7.Future<_i4.EmergencyAlertModel?> getAlertById(String? alertId) =>
      (super.noSuchMethod(
            Invocation.method(#getAlertById, [alertId]),
            returnValue: _i7.Future<_i4.EmergencyAlertModel?>.value(),
          )
          as _i7.Future<_i4.EmergencyAlertModel?>);

  @override
  _i7.Future<List<_i4.EmergencyAlertModel>> getUserAlerts({
    _i4.EmergencyAlertStatus? status,
    DateTime? since,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUserAlerts, [], {
              #status: status,
              #since: since,
            }),
            returnValue: _i7.Future<List<_i4.EmergencyAlertModel>>.value(
              <_i4.EmergencyAlertModel>[],
            ),
          )
          as _i7.Future<List<_i4.EmergencyAlertModel>>);

  @override
  _i7.Stream<List<_i4.EmergencyAlertModel>> watchActiveAlerts() =>
      (super.noSuchMethod(
            Invocation.method(#watchActiveAlerts, []),
            returnValue: _i7.Stream<List<_i4.EmergencyAlertModel>>.empty(),
          )
          as _i7.Stream<List<_i4.EmergencyAlertModel>>);

  @override
  _i7.Stream<List<_i4.EmergencyAlertModel>> watchReceivedAlerts() =>
      (super.noSuchMethod(
            Invocation.method(#watchReceivedAlerts, []),
            returnValue: _i7.Stream<List<_i4.EmergencyAlertModel>>.empty(),
          )
          as _i7.Stream<List<_i4.EmergencyAlertModel>>);

  @override
  _i7.Future<List<_i8.HospitalModel>> findNearestHospitals({
    required double? latitude,
    required double? longitude,
    double? maxDistanceKm = 50.0,
    int? limit = 10,
    bool? onlyEmergency = true,
    bool? only24_7 = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#findNearestHospitals, [], {
              #latitude: latitude,
              #longitude: longitude,
              #maxDistanceKm: maxDistanceKm,
              #limit: limit,
              #onlyEmergency: onlyEmergency,
              #only24_7: only24_7,
            }),
            returnValue: _i7.Future<List<_i8.HospitalModel>>.value(
              <_i8.HospitalModel>[],
            ),
          )
          as _i7.Future<List<_i8.HospitalModel>>);

  @override
  _i7.Future<List<_i8.HospitalModel>> searchHospitals({
    required String? searchTerm,
    String? city,
    String? state,
    int? limit = 20,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchHospitals, [], {
              #searchTerm: searchTerm,
              #city: city,
              #state: state,
              #limit: limit,
            }),
            returnValue: _i7.Future<List<_i8.HospitalModel>>.value(
              <_i8.HospitalModel>[],
            ),
          )
          as _i7.Future<List<_i8.HospitalModel>>);

  @override
  _i7.Future<_i8.HospitalModel?> getHospitalById({
    required String? hospitalId,
    double? userLatitude,
    double? userLongitude,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getHospitalById, [], {
              #hospitalId: hospitalId,
              #userLatitude: userLatitude,
              #userLongitude: userLongitude,
            }),
            returnValue: _i7.Future<_i8.HospitalModel?>.value(),
          )
          as _i7.Future<_i8.HospitalModel?>);

  @override
  _i7.Future<List<_i8.HospitalModel>> getHospitalsByLocation({
    String? city,
    String? state,
    int? limit = 50,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getHospitalsByLocation, [], {
              #city: city,
              #state: state,
              #limit: limit,
            }),
            returnValue: _i7.Future<List<_i8.HospitalModel>>.value(
              <_i8.HospitalModel>[],
            ),
          )
          as _i7.Future<List<_i8.HospitalModel>>);
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i9.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i5.Position> getCurrentLocation() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentLocation, []),
            returnValue: _i7.Future<_i5.Position>.value(
              _FakePosition_3(this, Invocation.method(#getCurrentLocation, [])),
            ),
          )
          as _i7.Future<_i5.Position>);

  @override
  _i7.Future<Map<String, double>?> getCurrentCoordinates() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentCoordinates, []),
            returnValue: _i7.Future<Map<String, double>?>.value(),
          )
          as _i7.Future<Map<String, double>?>);

  @override
  _i7.Stream<_i5.Position> watchLocation({
    _i5.LocationAccuracy? accuracy = _i5.LocationAccuracy.high,
    int? distanceFilter = 10,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watchLocation, [], {
              #accuracy: accuracy,
              #distanceFilter: distanceFilter,
            }),
            returnValue: _i7.Stream<_i5.Position>.empty(),
          )
          as _i7.Stream<_i5.Position>);

  @override
  _i7.Future<bool> hasLocationPermission() =>
      (super.noSuchMethod(
            Invocation.method(#hasLocationPermission, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> requestLocationPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestLocationPermission, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  _i7.Future<bool> openLocationSettings() =>
      (super.noSuchMethod(
            Invocation.method(#openLocationSettings, []),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  double getDistanceBetween({
    required double? startLatitude,
    required double? startLongitude,
    required double? endLatitude,
    required double? endLongitude,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getDistanceBetween, [], {
              #startLatitude: startLatitude,
              #startLongitude: startLongitude,
              #endLatitude: endLatitude,
              #endLongitude: endLongitude,
            }),
            returnValue: 0.0,
          )
          as double);

  @override
  double getBearingBetween({
    required double? startLatitude,
    required double? startLongitude,
    required double? endLatitude,
    required double? endLongitude,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBearingBetween, [], {
              #startLatitude: startLatitude,
              #startLongitude: startLongitude,
              #endLatitude: endLatitude,
              #endLongitude: endLongitude,
            }),
            returnValue: 0.0,
          )
          as double);
}
