// Mocks generated by Mockito 5.4.6 from annotations
// in travel_crew/test/features/trip_invites/domain/usecases/revoke_invite_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:travel_crew/features/trip_invites/domain/entities/invite_entity.dart'
    as _i2;
import 'package:travel_crew/features/trip_invites/domain/repositories/invite_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeInviteEntity_0 extends _i1.SmartFake implements _i2.InviteEntity {
  _FakeInviteEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [InviteRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockInviteRepository extends _i1.Mock implements _i3.InviteRepository {
  MockInviteRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.InviteEntity> generateInvite({
    required String? tripId,
    required String? email,
    String? phoneNumber,
    int? expiresInDays = 7,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#generateInvite, [], {
              #tripId: tripId,
              #email: email,
              #phoneNumber: phoneNumber,
              #expiresInDays: expiresInDays,
            }),
            returnValue: _i4.Future<_i2.InviteEntity>.value(
              _FakeInviteEntity_0(
                this,
                Invocation.method(#generateInvite, [], {
                  #tripId: tripId,
                  #email: email,
                  #phoneNumber: phoneNumber,
                  #expiresInDays: expiresInDays,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.InviteEntity>);

  @override
  _i4.Future<_i2.InviteEntity> acceptInvite({
    required String? inviteCode,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#acceptInvite, [], {
              #inviteCode: inviteCode,
              #userId: userId,
            }),
            returnValue: _i4.Future<_i2.InviteEntity>.value(
              _FakeInviteEntity_0(
                this,
                Invocation.method(#acceptInvite, [], {
                  #inviteCode: inviteCode,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.InviteEntity>);

  @override
  _i4.Future<void> rejectInvite({
    required String? inviteCode,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rejectInvite, [], {
              #inviteCode: inviteCode,
              #userId: userId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> revokeInvite({
    required String? inviteId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#revokeInvite, [], {
              #inviteId: inviteId,
              #userId: userId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.InviteEntity>> getTripInvites({
    required String? tripId,
    bool? includeExpired = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTripInvites, [], {
              #tripId: tripId,
              #includeExpired: includeExpired,
            }),
            returnValue: _i4.Future<List<_i2.InviteEntity>>.value(
              <_i2.InviteEntity>[],
            ),
          )
          as _i4.Future<List<_i2.InviteEntity>>);

  @override
  _i4.Future<_i2.InviteEntity?> getInviteByCode(String? inviteCode) =>
      (super.noSuchMethod(
            Invocation.method(#getInviteByCode, [inviteCode]),
            returnValue: _i4.Future<_i2.InviteEntity?>.value(),
          )
          as _i4.Future<_i2.InviteEntity?>);

  @override
  _i4.Future<List<_i2.InviteEntity>> getInvitesSentByUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getInvitesSentByUser, [userId]),
            returnValue: _i4.Future<List<_i2.InviteEntity>>.value(
              <_i2.InviteEntity>[],
            ),
          )
          as _i4.Future<List<_i2.InviteEntity>>);

  @override
  _i4.Future<List<_i2.InviteEntity>> getPendingInvitesForEmail(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#getPendingInvitesForEmail, [email]),
            returnValue: _i4.Future<List<_i2.InviteEntity>>.value(
              <_i2.InviteEntity>[],
            ),
          )
          as _i4.Future<List<_i2.InviteEntity>>);

  @override
  _i4.Future<_i2.InviteEntity> resendInvite(String? inviteId) =>
      (super.noSuchMethod(
            Invocation.method(#resendInvite, [inviteId]),
            returnValue: _i4.Future<_i2.InviteEntity>.value(
              _FakeInviteEntity_0(
                this,
                Invocation.method(#resendInvite, [inviteId]),
              ),
            ),
          )
          as _i4.Future<_i2.InviteEntity>);

  @override
  _i4.Future<void> deleteExpiredInvites({String? tripId}) =>
      (super.noSuchMethod(
            Invocation.method(#deleteExpiredInvites, [], {#tripId: tripId}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
