// Mocks generated by Mockito 5.4.6 from annotations
// in travel_crew/test/features/checklists/data/repositories/checklist_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:travel_crew/features/checklists/data/datasources/checklist_remote_datasource.dart'
    as _i3;
import 'package:travel_crew/shared/models/checklist_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeChecklistModel_0 extends _i1.SmartFake
    implements _i2.ChecklistModel {
  _FakeChecklistModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChecklistItemModel_1 extends _i1.SmartFake
    implements _i2.ChecklistItemModel {
  _FakeChecklistItemModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChecklistRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockChecklistRemoteDataSource extends _i1.Mock
    implements _i3.ChecklistRemoteDataSource {
  MockChecklistRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.ChecklistModel>> getTripChecklists(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#getTripChecklists, [tripId]),
            returnValue: _i4.Future<List<_i2.ChecklistModel>>.value(
              <_i2.ChecklistModel>[],
            ),
          )
          as _i4.Future<List<_i2.ChecklistModel>>);

  @override
  _i4.Future<_i2.ChecklistModel?> getChecklist(String? checklistId) =>
      (super.noSuchMethod(
            Invocation.method(#getChecklist, [checklistId]),
            returnValue: _i4.Future<_i2.ChecklistModel?>.value(),
          )
          as _i4.Future<_i2.ChecklistModel?>);

  @override
  _i4.Future<List<_i2.ChecklistItemModel>> getChecklistItems(
    String? checklistId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getChecklistItems, [checklistId]),
            returnValue: _i4.Future<List<_i2.ChecklistItemModel>>.value(
              <_i2.ChecklistItemModel>[],
            ),
          )
          as _i4.Future<List<_i2.ChecklistItemModel>>);

  @override
  _i4.Future<_i2.ChecklistModel> upsertChecklist(
    _i2.ChecklistModel? checklist,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#upsertChecklist, [checklist]),
            returnValue: _i4.Future<_i2.ChecklistModel>.value(
              _FakeChecklistModel_0(
                this,
                Invocation.method(#upsertChecklist, [checklist]),
              ),
            ),
          )
          as _i4.Future<_i2.ChecklistModel>);

  @override
  _i4.Future<_i2.ChecklistItemModel> upsertChecklistItem(
    _i2.ChecklistItemModel? item,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#upsertChecklistItem, [item]),
            returnValue: _i4.Future<_i2.ChecklistItemModel>.value(
              _FakeChecklistItemModel_1(
                this,
                Invocation.method(#upsertChecklistItem, [item]),
              ),
            ),
          )
          as _i4.Future<_i2.ChecklistItemModel>);

  @override
  _i4.Future<void> deleteChecklist(String? checklistId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteChecklist, [checklistId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteChecklistItem(String? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteChecklistItem, [itemId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.ChecklistItemModel> toggleItemCompletion({
    required String? itemId,
    required bool? isCompleted,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#toggleItemCompletion, [], {
              #itemId: itemId,
              #isCompleted: isCompleted,
              #userId: userId,
            }),
            returnValue: _i4.Future<_i2.ChecklistItemModel>.value(
              _FakeChecklistItemModel_1(
                this,
                Invocation.method(#toggleItemCompletion, [], {
                  #itemId: itemId,
                  #isCompleted: isCompleted,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ChecklistItemModel>);
}
