// Mocks generated by Mockito 5.4.6 from annotations
// in travel_crew/test/features/checklists/domain/usecases/manage_checklist_items_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:travel_crew/features/checklists/domain/entities/checklist_entity.dart'
    as _i2;
import 'package:travel_crew/features/checklists/domain/repositories/checklist_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeChecklistWithItemsEntity_0 extends _i1.SmartFake
    implements _i2.ChecklistWithItemsEntity {
  _FakeChecklistWithItemsEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChecklistEntity_1 extends _i1.SmartFake
    implements _i2.ChecklistEntity {
  _FakeChecklistEntity_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChecklistItemEntity_2 extends _i1.SmartFake
    implements _i2.ChecklistItemEntity {
  _FakeChecklistItemEntity_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChecklistRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockChecklistRepository extends _i1.Mock
    implements _i3.ChecklistRepository {
  MockChecklistRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.ChecklistEntity>> getTripChecklists(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#getTripChecklists, [tripId]),
            returnValue: _i4.Future<List<_i2.ChecklistEntity>>.value(
              <_i2.ChecklistEntity>[],
            ),
          )
          as _i4.Future<List<_i2.ChecklistEntity>>);

  @override
  _i4.Future<_i2.ChecklistWithItemsEntity> getChecklistWithItems(
    String? checklistId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getChecklistWithItems, [checklistId]),
            returnValue: _i4.Future<_i2.ChecklistWithItemsEntity>.value(
              _FakeChecklistWithItemsEntity_0(
                this,
                Invocation.method(#getChecklistWithItems, [checklistId]),
              ),
            ),
          )
          as _i4.Future<_i2.ChecklistWithItemsEntity>);

  @override
  _i4.Future<_i2.ChecklistEntity> createChecklist({
    required String? tripId,
    required String? name,
    required String? createdBy,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createChecklist, [], {
              #tripId: tripId,
              #name: name,
              #createdBy: createdBy,
            }),
            returnValue: _i4.Future<_i2.ChecklistEntity>.value(
              _FakeChecklistEntity_1(
                this,
                Invocation.method(#createChecklist, [], {
                  #tripId: tripId,
                  #name: name,
                  #createdBy: createdBy,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ChecklistEntity>);

  @override
  _i4.Future<_i2.ChecklistEntity> updateChecklist({
    required String? checklistId,
    required String? name,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateChecklist, [], {
              #checklistId: checklistId,
              #name: name,
            }),
            returnValue: _i4.Future<_i2.ChecklistEntity>.value(
              _FakeChecklistEntity_1(
                this,
                Invocation.method(#updateChecklist, [], {
                  #checklistId: checklistId,
                  #name: name,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ChecklistEntity>);

  @override
  _i4.Future<void> deleteChecklist(String? checklistId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteChecklist, [checklistId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.ChecklistItemEntity> addChecklistItem({
    required String? checklistId,
    required String? title,
    String? assignedTo,
    int? orderIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addChecklistItem, [], {
              #checklistId: checklistId,
              #title: title,
              #assignedTo: assignedTo,
              #orderIndex: orderIndex,
            }),
            returnValue: _i4.Future<_i2.ChecklistItemEntity>.value(
              _FakeChecklistItemEntity_2(
                this,
                Invocation.method(#addChecklistItem, [], {
                  #checklistId: checklistId,
                  #title: title,
                  #assignedTo: assignedTo,
                  #orderIndex: orderIndex,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ChecklistItemEntity>);

  @override
  _i4.Future<_i2.ChecklistItemEntity> updateChecklistItem({
    required String? itemId,
    String? title,
    bool? isCompleted,
    String? assignedTo,
    int? orderIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateChecklistItem, [], {
              #itemId: itemId,
              #title: title,
              #isCompleted: isCompleted,
              #assignedTo: assignedTo,
              #orderIndex: orderIndex,
            }),
            returnValue: _i4.Future<_i2.ChecklistItemEntity>.value(
              _FakeChecklistItemEntity_2(
                this,
                Invocation.method(#updateChecklistItem, [], {
                  #itemId: itemId,
                  #title: title,
                  #isCompleted: isCompleted,
                  #assignedTo: assignedTo,
                  #orderIndex: orderIndex,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ChecklistItemEntity>);

  @override
  _i4.Future<_i2.ChecklistItemEntity> toggleItemCompletion({
    required String? itemId,
    required bool? isCompleted,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#toggleItemCompletion, [], {
              #itemId: itemId,
              #isCompleted: isCompleted,
              #userId: userId,
            }),
            returnValue: _i4.Future<_i2.ChecklistItemEntity>.value(
              _FakeChecklistItemEntity_2(
                this,
                Invocation.method(#toggleItemCompletion, [], {
                  #itemId: itemId,
                  #isCompleted: isCompleted,
                  #userId: userId,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ChecklistItemEntity>);

  @override
  _i4.Future<void> deleteChecklistItem(String? itemId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteChecklistItem, [itemId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> reorderItems({
    required String? checklistId,
    required List<String>? itemIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#reorderItems, [], {
              #checklistId: checklistId,
              #itemIds: itemIds,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<_i2.ChecklistEntity>> watchTripChecklists(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#watchTripChecklists, [tripId]),
            returnValue: _i4.Stream<List<_i2.ChecklistEntity>>.empty(),
          )
          as _i4.Stream<List<_i2.ChecklistEntity>>);

  @override
  _i4.Stream<_i2.ChecklistWithItemsEntity> watchChecklistWithItems(
    String? checklistId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#watchChecklistWithItems, [checklistId]),
            returnValue: _i4.Stream<_i2.ChecklistWithItemsEntity>.empty(),
          )
          as _i4.Stream<_i2.ChecklistWithItemsEntity>);
}
