// Mocks generated by Mockito 5.4.6 from annotations
// in travel_crew/test/features/trips/domain/usecases/get_user_stats_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:travel_crew/features/trips/domain/repositories/trip_repository.dart'
    as _i4;
import 'package:travel_crew/features/trips/domain/usecases/get_user_stats_usecase.dart'
    as _i3;
import 'package:travel_crew/shared/models/trip_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTripModel_0 extends _i1.SmartFake implements _i2.TripModel {
  _FakeTripModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTripWithMembers_1 extends _i1.SmartFake
    implements _i2.TripWithMembers {
  _FakeTripWithMembers_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTripMemberModel_2 extends _i1.SmartFake
    implements _i2.TripMemberModel {
  _FakeTripMemberModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserTravelStats_3 extends _i1.SmartFake
    implements _i3.UserTravelStats {
  _FakeUserTravelStats_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TripRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTripRepository extends _i1.Mock implements _i4.TripRepository {
  MockTripRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.TripModel> createTrip({
    required String? name,
    String? description,
    String? destination,
    DateTime? startDate,
    DateTime? endDate,
    String? coverImageUrl,
    double? cost,
    String? currency,
    bool? isPublic = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTrip, [], {
              #name: name,
              #description: description,
              #destination: destination,
              #startDate: startDate,
              #endDate: endDate,
              #coverImageUrl: coverImageUrl,
              #cost: cost,
              #currency: currency,
              #isPublic: isPublic,
            }),
            returnValue: _i5.Future<_i2.TripModel>.value(
              _FakeTripModel_0(
                this,
                Invocation.method(#createTrip, [], {
                  #name: name,
                  #description: description,
                  #destination: destination,
                  #startDate: startDate,
                  #endDate: endDate,
                  #coverImageUrl: coverImageUrl,
                  #cost: cost,
                  #currency: currency,
                  #isPublic: isPublic,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.TripModel>);

  @override
  _i5.Future<List<_i2.TripWithMembers>> getUserTrips() =>
      (super.noSuchMethod(
            Invocation.method(#getUserTrips, []),
            returnValue: _i5.Future<List<_i2.TripWithMembers>>.value(
              <_i2.TripWithMembers>[],
            ),
          )
          as _i5.Future<List<_i2.TripWithMembers>>);

  @override
  _i5.Future<_i2.TripWithMembers> getTripById(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#getTripById, [tripId]),
            returnValue: _i5.Future<_i2.TripWithMembers>.value(
              _FakeTripWithMembers_1(
                this,
                Invocation.method(#getTripById, [tripId]),
              ),
            ),
          )
          as _i5.Future<_i2.TripWithMembers>);

  @override
  _i5.Future<_i2.TripModel> updateTrip({
    required String? tripId,
    String? name,
    String? description,
    String? destination,
    DateTime? startDate,
    DateTime? endDate,
    String? coverImageUrl,
    bool? isCompleted,
    DateTime? completedAt,
    double? rating,
    double? cost,
    String? currency,
    bool? isPublic,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTrip, [], {
              #tripId: tripId,
              #name: name,
              #description: description,
              #destination: destination,
              #startDate: startDate,
              #endDate: endDate,
              #coverImageUrl: coverImageUrl,
              #isCompleted: isCompleted,
              #completedAt: completedAt,
              #rating: rating,
              #cost: cost,
              #currency: currency,
              #isPublic: isPublic,
            }),
            returnValue: _i5.Future<_i2.TripModel>.value(
              _FakeTripModel_0(
                this,
                Invocation.method(#updateTrip, [], {
                  #tripId: tripId,
                  #name: name,
                  #description: description,
                  #destination: destination,
                  #startDate: startDate,
                  #endDate: endDate,
                  #coverImageUrl: coverImageUrl,
                  #isCompleted: isCompleted,
                  #completedAt: completedAt,
                  #rating: rating,
                  #cost: cost,
                  #currency: currency,
                  #isPublic: isPublic,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.TripModel>);

  @override
  _i5.Future<void> deleteTrip(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTrip, [tripId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i2.TripMemberModel>> getTripMembers(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#getTripMembers, [tripId]),
            returnValue: _i5.Future<List<_i2.TripMemberModel>>.value(
              <_i2.TripMemberModel>[],
            ),
          )
          as _i5.Future<List<_i2.TripMemberModel>>);

  @override
  _i5.Future<_i2.TripMemberModel> addMember({
    required String? tripId,
    required String? userId,
    String? role,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addMember, [], {
              #tripId: tripId,
              #userId: userId,
              #role: role,
            }),
            returnValue: _i5.Future<_i2.TripMemberModel>.value(
              _FakeTripMemberModel_2(
                this,
                Invocation.method(#addMember, [], {
                  #tripId: tripId,
                  #userId: userId,
                  #role: role,
                }),
              ),
            ),
          )
          as _i5.Future<_i2.TripMemberModel>);

  @override
  _i5.Future<void> removeMember({
    required String? tripId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeMember, [], {
              #tripId: tripId,
              #userId: userId,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Stream<List<_i2.TripWithMembers>> watchUserTrips() =>
      (super.noSuchMethod(
            Invocation.method(#watchUserTrips, []),
            returnValue: _i5.Stream<List<_i2.TripWithMembers>>.empty(),
          )
          as _i5.Stream<List<_i2.TripWithMembers>>);

  @override
  _i5.Stream<_i2.TripWithMembers> watchTrip(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#watchTrip, [tripId]),
            returnValue: _i5.Stream<_i2.TripWithMembers>.empty(),
          )
          as _i5.Stream<_i2.TripWithMembers>);

  @override
  _i5.Future<_i3.UserTravelStats> getUserStats() =>
      (super.noSuchMethod(
            Invocation.method(#getUserStats, []),
            returnValue: _i5.Future<_i3.UserTravelStats>.value(
              _FakeUserTravelStats_3(
                this,
                Invocation.method(#getUserStats, []),
              ),
            ),
          )
          as _i5.Future<_i3.UserTravelStats>);

  @override
  _i5.Stream<_i3.UserTravelStats> watchUserStats() =>
      (super.noSuchMethod(
            Invocation.method(#watchUserStats, []),
            returnValue: _i5.Stream<_i3.UserTravelStats>.empty(),
          )
          as _i5.Stream<_i3.UserTravelStats>);

  @override
  _i5.Future<List<_i2.TripWithMembers>> getDiscoverableTrips() =>
      (super.noSuchMethod(
            Invocation.method(#getDiscoverableTrips, []),
            returnValue: _i5.Future<List<_i2.TripWithMembers>>.value(
              <_i2.TripWithMembers>[],
            ),
          )
          as _i5.Future<List<_i2.TripWithMembers>>);

  @override
  _i5.Future<void> joinTrip(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#joinTrip, [tripId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String> copyTrip({
    required String? sourceTripId,
    required String? newName,
    required DateTime? newStartDate,
    required DateTime? newEndDate,
    bool? copyItinerary = true,
    bool? copyChecklists = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#copyTrip, [], {
              #sourceTripId: sourceTripId,
              #newName: newName,
              #newStartDate: newStartDate,
              #newEndDate: newEndDate,
              #copyItinerary: copyItinerary,
              #copyChecklists: copyChecklists,
            }),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#copyTrip, [], {
                  #sourceTripId: sourceTripId,
                  #newName: newName,
                  #newStartDate: newStartDate,
                  #newEndDate: newEndDate,
                  #copyItinerary: copyItinerary,
                  #copyChecklists: copyChecklists,
                }),
              ),
            ),
          )
          as _i5.Future<String>);
}
