// Mocks generated by Mockito 5.4.6 from annotations
// in travel_crew/test/features/auth/integration/profile_photo_upload_integration_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;
import 'dart:io' as _i9;
import 'dart:typed_data' as _i10;

import 'package:image_picker/image_picker.dart' as _i11;
import 'package:image_picker_platform_interface/image_picker_platform_interface.dart'
    as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:storage_client/src/fetch.dart' as _i4;
import 'package:supabase_flutter/supabase_flutter.dart' as _i3;
import 'package:travel_crew/features/auth/data/datasources/auth_remote_datasource.dart'
    as _i6;
import 'package:travel_crew/features/auth/data/models/user_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeUserModel_0 extends _i1.SmartFake implements _i2.UserModel {
  _FakeUserModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFunctionsClient_1 extends _i1.SmartFake
    implements _i3.FunctionsClient {
  _FakeFunctionsClient_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseStorageClient_2 extends _i1.SmartFake
    implements _i3.SupabaseStorageClient {
  _FakeSupabaseStorageClient_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeClient_3 extends _i1.SmartFake
    implements _i3.RealtimeClient {
  _FakeRealtimeClient_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestClient_4 extends _i1.SmartFake
    implements _i3.PostgrestClient {
  _FakePostgrestClient_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGoTrueClient_5 extends _i1.SmartFake implements _i3.GoTrueClient {
  _FakeGoTrueClient_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQueryBuilder_6 extends _i1.SmartFake
    implements _i3.SupabaseQueryBuilder {
  _FakeSupabaseQueryBuilder_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSupabaseQuerySchema_7 extends _i1.SmartFake
    implements _i3.SupabaseQuerySchema {
  _FakeSupabaseQuerySchema_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostgrestFilterBuilder_8<T1> extends _i1.SmartFake
    implements _i3.PostgrestFilterBuilder<T1> {
  _FakePostgrestFilterBuilder_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRealtimeChannel_9 extends _i1.SmartFake
    implements _i3.RealtimeChannel {
  _FakeRealtimeChannel_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFetch_10 extends _i1.SmartFake implements _i4.Fetch {
  _FakeFetch_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStorageFileApi_11 extends _i1.SmartFake
    implements _i3.StorageFileApi {
  _FakeStorageFileApi_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBucket_12 extends _i1.SmartFake implements _i3.Bucket {
  _FakeBucket_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSignedUploadURLResponse_13 extends _i1.SmartFake
    implements _i3.SignedUploadURLResponse {
  _FakeSignedUploadURLResponse_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileObjectV2_14 extends _i1.SmartFake implements _i3.FileObjectV2 {
  _FakeFileObjectV2_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLostDataResponse_15 extends _i1.SmartFake
    implements _i5.LostDataResponse {
  _FakeLostDataResponse_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AuthRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRemoteDataSource extends _i1.Mock
    implements _i6.AuthRemoteDataSource {
  MockAuthRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Stream<_i3.User?> get authStateChanges =>
      (super.noSuchMethod(
            Invocation.getter(#authStateChanges),
            returnValue: _i7.Stream<_i3.User?>.empty(),
          )
          as _i7.Stream<_i3.User?>);

  @override
  bool get isAuthenticated =>
      (super.noSuchMethod(
            Invocation.getter(#isAuthenticated),
            returnValue: false,
          )
          as bool);

  @override
  _i7.Future<_i2.UserModel> signUp({
    required String? email,
    required String? password,
    required String? fullName,
    String? phoneNumber,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [], {
              #email: email,
              #password: password,
              #fullName: fullName,
              #phoneNumber: phoneNumber,
            }),
            returnValue: _i7.Future<_i2.UserModel>.value(
              _FakeUserModel_0(
                this,
                Invocation.method(#signUp, [], {
                  #email: email,
                  #password: password,
                  #fullName: fullName,
                  #phoneNumber: phoneNumber,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.UserModel>);

  @override
  _i7.Future<_i2.UserModel> signIn({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#signIn, [], {
              #email: email,
              #password: password,
            }),
            returnValue: _i7.Future<_i2.UserModel>.value(
              _FakeUserModel_0(
                this,
                Invocation.method(#signIn, [], {
                  #email: email,
                  #password: password,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.UserModel>);

  @override
  _i7.Future<void> signOut() =>
      (super.noSuchMethod(
            Invocation.method(#signOut, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.UserModel?> getCurrentUser() =>
      (super.noSuchMethod(
            Invocation.method(#getCurrentUser, []),
            returnValue: _i7.Future<_i2.UserModel?>.value(),
          )
          as _i7.Future<_i2.UserModel?>);

  @override
  _i7.Future<_i2.UserModel> updateProfile({
    required String? userId,
    String? fullName,
    String? phoneNumber,
    String? avatarUrl,
    String? bio,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #userId: userId,
              #fullName: fullName,
              #phoneNumber: phoneNumber,
              #avatarUrl: avatarUrl,
              #bio: bio,
            }),
            returnValue: _i7.Future<_i2.UserModel>.value(
              _FakeUserModel_0(
                this,
                Invocation.method(#updateProfile, [], {
                  #userId: userId,
                  #fullName: fullName,
                  #phoneNumber: phoneNumber,
                  #avatarUrl: avatarUrl,
                  #bio: bio,
                }),
              ),
            ),
          )
          as _i7.Future<_i2.UserModel>);

  @override
  _i7.Future<void> resetPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [email]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> changePassword({
    required String? currentPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {
              #currentPassword: currentPassword,
              #newPassword: newPassword,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> updatePassword({required String? newPassword}) =>
      (super.noSuchMethod(
            Invocation.method(#updatePassword, [], {#newPassword: newPassword}),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<void> verifyOtpAndUpdatePassword({
    required String? token,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtpAndUpdatePassword, [], {
              #token: token,
              #newPassword: newPassword,
            }),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [SupabaseClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseClient extends _i1.Mock implements _i3.SupabaseClient {
  MockSupabaseClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.FunctionsClient get functions =>
      (super.noSuchMethod(
            Invocation.getter(#functions),
            returnValue: _FakeFunctionsClient_1(
              this,
              Invocation.getter(#functions),
            ),
          )
          as _i3.FunctionsClient);

  @override
  _i3.SupabaseStorageClient get storage =>
      (super.noSuchMethod(
            Invocation.getter(#storage),
            returnValue: _FakeSupabaseStorageClient_2(
              this,
              Invocation.getter(#storage),
            ),
          )
          as _i3.SupabaseStorageClient);

  @override
  _i3.RealtimeClient get realtime =>
      (super.noSuchMethod(
            Invocation.getter(#realtime),
            returnValue: _FakeRealtimeClient_3(
              this,
              Invocation.getter(#realtime),
            ),
          )
          as _i3.RealtimeClient);

  @override
  _i3.PostgrestClient get rest =>
      (super.noSuchMethod(
            Invocation.getter(#rest),
            returnValue: _FakePostgrestClient_4(this, Invocation.getter(#rest)),
          )
          as _i3.PostgrestClient);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i3.GoTrueClient get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeGoTrueClient_5(this, Invocation.getter(#auth)),
          )
          as _i3.GoTrueClient);

  @override
  set functions(_i3.FunctionsClient? _functions) => super.noSuchMethod(
    Invocation.setter(#functions, _functions),
    returnValueForMissingStub: null,
  );

  @override
  set storage(_i3.SupabaseStorageClient? _storage) => super.noSuchMethod(
    Invocation.setter(#storage, _storage),
    returnValueForMissingStub: null,
  );

  @override
  set realtime(_i3.RealtimeClient? _realtime) => super.noSuchMethod(
    Invocation.setter(#realtime, _realtime),
    returnValueForMissingStub: null,
  );

  @override
  set rest(_i3.PostgrestClient? _rest) => super.noSuchMethod(
    Invocation.setter(#rest, _rest),
    returnValueForMissingStub: null,
  );

  @override
  set headers(Map<String, String>? headers) => super.noSuchMethod(
    Invocation.setter(#headers, headers),
    returnValueForMissingStub: null,
  );

  @override
  _i3.SupabaseQueryBuilder from(String? table) =>
      (super.noSuchMethod(
            Invocation.method(#from, [table]),
            returnValue: _FakeSupabaseQueryBuilder_6(
              this,
              Invocation.method(#from, [table]),
            ),
          )
          as _i3.SupabaseQueryBuilder);

  @override
  _i3.SupabaseQuerySchema schema(String? schema) =>
      (super.noSuchMethod(
            Invocation.method(#schema, [schema]),
            returnValue: _FakeSupabaseQuerySchema_7(
              this,
              Invocation.method(#schema, [schema]),
            ),
          )
          as _i3.SupabaseQuerySchema);

  @override
  _i3.PostgrestFilterBuilder<T> rpc<T>(
    String? fn, {
    Map<String, dynamic>? params,
    dynamic get = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            returnValue: _FakePostgrestFilterBuilder_8<T>(
              this,
              Invocation.method(#rpc, [fn], {#params: params, #get: get}),
            ),
          )
          as _i3.PostgrestFilterBuilder<T>);

  @override
  _i3.RealtimeChannel channel(
    String? name, {
    _i3.RealtimeChannelConfig? opts = const _i3.RealtimeChannelConfig(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#channel, [name], {#opts: opts}),
            returnValue: _FakeRealtimeChannel_9(
              this,
              Invocation.method(#channel, [name], {#opts: opts}),
            ),
          )
          as _i3.RealtimeChannel);

  @override
  List<_i3.RealtimeChannel> getChannels() =>
      (super.noSuchMethod(
            Invocation.method(#getChannels, []),
            returnValue: <_i3.RealtimeChannel>[],
          )
          as List<_i3.RealtimeChannel>);

  @override
  _i7.Future<String> removeChannel(_i3.RealtimeChannel? channel) =>
      (super.noSuchMethod(
            Invocation.method(#removeChannel, [channel]),
            returnValue: _i7.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#removeChannel, [channel]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<List<String>> removeAllChannels() =>
      (super.noSuchMethod(
            Invocation.method(#removeAllChannels, []),
            returnValue: _i7.Future<List<String>>.value(<String>[]),
          )
          as _i7.Future<List<String>>);

  @override
  _i7.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);
}

/// A class which mocks [SupabaseStorageClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockSupabaseStorageClient extends _i1.Mock
    implements _i3.SupabaseStorageClient {
  MockSupabaseStorageClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get url =>
      (super.noSuchMethod(
            Invocation.getter(#url),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#url)),
          )
          as String);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i4.Fetch get storageFetch =>
      (super.noSuchMethod(
            Invocation.getter(#storageFetch),
            returnValue: _FakeFetch_10(this, Invocation.getter(#storageFetch)),
          )
          as _i4.Fetch);

  @override
  set storageFetch(_i4.Fetch? _storageFetch) => super.noSuchMethod(
    Invocation.setter(#storageFetch, _storageFetch),
    returnValueForMissingStub: null,
  );

  @override
  _i3.StorageFileApi from(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#from, [id]),
            returnValue: _FakeStorageFileApi_11(
              this,
              Invocation.method(#from, [id]),
            ),
          )
          as _i3.StorageFileApi);

  @override
  void setAuth(String? jwt) => super.noSuchMethod(
    Invocation.method(#setAuth, [jwt]),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<List<_i3.Bucket>> listBuckets() =>
      (super.noSuchMethod(
            Invocation.method(#listBuckets, []),
            returnValue: _i7.Future<List<_i3.Bucket>>.value(<_i3.Bucket>[]),
          )
          as _i7.Future<List<_i3.Bucket>>);

  @override
  _i7.Future<_i3.Bucket> getBucket(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getBucket, [id]),
            returnValue: _i7.Future<_i3.Bucket>.value(
              _FakeBucket_12(this, Invocation.method(#getBucket, [id])),
            ),
          )
          as _i7.Future<_i3.Bucket>);

  @override
  _i7.Future<String> createBucket(
    String? id, [
    _i3.BucketOptions? bucketOptions = const _i3.BucketOptions(public: false),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#createBucket, [id, bucketOptions]),
            returnValue: _i7.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#createBucket, [id, bucketOptions]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<String> updateBucket(
    String? id,
    _i3.BucketOptions? bucketOptions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBucket, [id, bucketOptions]),
            returnValue: _i7.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#updateBucket, [id, bucketOptions]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<String> emptyBucket(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#emptyBucket, [id]),
            returnValue: _i7.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#emptyBucket, [id]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<String> deleteBucket(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBucket, [id]),
            returnValue: _i7.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#deleteBucket, [id]),
              ),
            ),
          )
          as _i7.Future<String>);
}

/// A class which mocks [StorageFileApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageFileApi extends _i1.Mock implements _i3.StorageFileApi {
  MockStorageFileApi() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get url =>
      (super.noSuchMethod(
            Invocation.getter(#url),
            returnValue: _i8.dummyValue<String>(this, Invocation.getter(#url)),
          )
          as String);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i7.Future<String> upload(
    String? path,
    _i9.File? file, {
    _i3.FileOptions? fileOptions = const _i3.FileOptions(),
    int? retryAttempts,
    _i3.StorageRetryController? retryController,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #upload,
              [path, file],
              {
                #fileOptions: fileOptions,
                #retryAttempts: retryAttempts,
                #retryController: retryController,
              },
            ),
            returnValue: _i7.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(
                  #upload,
                  [path, file],
                  {
                    #fileOptions: fileOptions,
                    #retryAttempts: retryAttempts,
                    #retryController: retryController,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<String> uploadBinary(
    String? path,
    _i10.Uint8List? data, {
    _i3.FileOptions? fileOptions = const _i3.FileOptions(),
    int? retryAttempts,
    _i3.StorageRetryController? retryController,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadBinary,
              [path, data],
              {
                #fileOptions: fileOptions,
                #retryAttempts: retryAttempts,
                #retryController: retryController,
              },
            ),
            returnValue: _i7.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(
                  #uploadBinary,
                  [path, data],
                  {
                    #fileOptions: fileOptions,
                    #retryAttempts: retryAttempts,
                    #retryController: retryController,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<String> uploadToSignedUrl(
    String? path,
    String? token,
    _i9.File? file, [
    _i3.FileOptions? fileOptions = const _i3.FileOptions(),
    int? retryAttempts,
    _i3.StorageRetryController? retryController,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#uploadToSignedUrl, [
              path,
              token,
              file,
              fileOptions,
              retryAttempts,
              retryController,
            ]),
            returnValue: _i7.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#uploadToSignedUrl, [
                  path,
                  token,
                  file,
                  fileOptions,
                  retryAttempts,
                  retryController,
                ]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<String> uploadBinaryToSignedUrl(
    String? path,
    String? token,
    _i10.Uint8List? data, [
    _i3.FileOptions? fileOptions = const _i3.FileOptions(),
    int? retryAttempts,
    _i3.StorageRetryController? retryController,
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#uploadBinaryToSignedUrl, [
              path,
              token,
              data,
              fileOptions,
              retryAttempts,
              retryController,
            ]),
            returnValue: _i7.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#uploadBinaryToSignedUrl, [
                  path,
                  token,
                  data,
                  fileOptions,
                  retryAttempts,
                  retryController,
                ]),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<_i3.SignedUploadURLResponse> createSignedUploadUrl(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#createSignedUploadUrl, [path]),
            returnValue: _i7.Future<_i3.SignedUploadURLResponse>.value(
              _FakeSignedUploadURLResponse_13(
                this,
                Invocation.method(#createSignedUploadUrl, [path]),
              ),
            ),
          )
          as _i7.Future<_i3.SignedUploadURLResponse>);

  @override
  _i7.Future<String> update(
    String? path,
    _i9.File? file, {
    _i3.FileOptions? fileOptions = const _i3.FileOptions(),
    int? retryAttempts,
    _i3.StorageRetryController? retryController,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #update,
              [path, file],
              {
                #fileOptions: fileOptions,
                #retryAttempts: retryAttempts,
                #retryController: retryController,
              },
            ),
            returnValue: _i7.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(
                  #update,
                  [path, file],
                  {
                    #fileOptions: fileOptions,
                    #retryAttempts: retryAttempts,
                    #retryController: retryController,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<String> updateBinary(
    String? path,
    _i10.Uint8List? data, {
    _i3.FileOptions? fileOptions = const _i3.FileOptions(),
    int? retryAttempts,
    _i3.StorageRetryController? retryController,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateBinary,
              [path, data],
              {
                #fileOptions: fileOptions,
                #retryAttempts: retryAttempts,
                #retryController: retryController,
              },
            ),
            returnValue: _i7.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(
                  #updateBinary,
                  [path, data],
                  {
                    #fileOptions: fileOptions,
                    #retryAttempts: retryAttempts,
                    #retryController: retryController,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<String> move(
    String? fromPath,
    String? toPath, {
    String? destinationBucket,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #move,
              [fromPath, toPath],
              {#destinationBucket: destinationBucket},
            ),
            returnValue: _i7.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(
                  #move,
                  [fromPath, toPath],
                  {#destinationBucket: destinationBucket},
                ),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<String> copy(
    String? fromPath,
    String? toPath, {
    String? destinationBucket,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #copy,
              [fromPath, toPath],
              {#destinationBucket: destinationBucket},
            ),
            returnValue: _i7.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(
                  #copy,
                  [fromPath, toPath],
                  {#destinationBucket: destinationBucket},
                ),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<String> createSignedUrl(
    String? path,
    int? expiresIn, {
    _i3.TransformOptions? transform,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createSignedUrl,
              [path, expiresIn],
              {#transform: transform},
            ),
            returnValue: _i7.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(
                  #createSignedUrl,
                  [path, expiresIn],
                  {#transform: transform},
                ),
              ),
            ),
          )
          as _i7.Future<String>);

  @override
  _i7.Future<List<_i3.SignedUrl>> createSignedUrls(
    List<String>? paths,
    int? expiresIn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createSignedUrls, [paths, expiresIn]),
            returnValue: _i7.Future<List<_i3.SignedUrl>>.value(
              <_i3.SignedUrl>[],
            ),
          )
          as _i7.Future<List<_i3.SignedUrl>>);

  @override
  _i7.Future<_i10.Uint8List> download(
    String? path, {
    _i3.TransformOptions? transform,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#download, [path], {#transform: transform}),
            returnValue: _i7.Future<_i10.Uint8List>.value(_i10.Uint8List(0)),
          )
          as _i7.Future<_i10.Uint8List>);

  @override
  _i7.Future<_i3.FileObjectV2> info(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#info, [path]),
            returnValue: _i7.Future<_i3.FileObjectV2>.value(
              _FakeFileObjectV2_14(this, Invocation.method(#info, [path])),
            ),
          )
          as _i7.Future<_i3.FileObjectV2>);

  @override
  _i7.Future<bool> exists(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#exists, [path]),
            returnValue: _i7.Future<bool>.value(false),
          )
          as _i7.Future<bool>);

  @override
  String getPublicUrl(String? path, {_i3.TransformOptions? transform}) =>
      (super.noSuchMethod(
            Invocation.method(#getPublicUrl, [path], {#transform: transform}),
            returnValue: _i8.dummyValue<String>(
              this,
              Invocation.method(#getPublicUrl, [path], {#transform: transform}),
            ),
          )
          as String);

  @override
  _i7.Future<List<_i3.FileObject>> remove(List<String>? paths) =>
      (super.noSuchMethod(
            Invocation.method(#remove, [paths]),
            returnValue: _i7.Future<List<_i3.FileObject>>.value(
              <_i3.FileObject>[],
            ),
          )
          as _i7.Future<List<_i3.FileObject>>);

  @override
  _i7.Future<List<_i3.FileObject>> list({
    String? path,
    _i3.SearchOptions? searchOptions = const _i3.SearchOptions(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#list, [], {
              #path: path,
              #searchOptions: searchOptions,
            }),
            returnValue: _i7.Future<List<_i3.FileObject>>.value(
              <_i3.FileObject>[],
            ),
          )
          as _i7.Future<List<_i3.FileObject>>);
}

/// A class which mocks [ImagePicker].
///
/// See the documentation for Mockito's code generation for more information.
class MockImagePicker extends _i1.Mock implements _i11.ImagePicker {
  MockImagePicker() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i5.XFile?> pickImage({
    required _i5.ImageSource? source,
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    _i5.CameraDevice? preferredCameraDevice = _i5.CameraDevice.rear,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickImage, [], {
              #source: source,
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
              #imageQuality: imageQuality,
              #preferredCameraDevice: preferredCameraDevice,
              #requestFullMetadata: requestFullMetadata,
            }),
            returnValue: _i7.Future<_i5.XFile?>.value(),
          )
          as _i7.Future<_i5.XFile?>);

  @override
  _i7.Future<List<_i5.XFile>> pickMultiImage({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    int? limit,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickMultiImage, [], {
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
              #imageQuality: imageQuality,
              #limit: limit,
              #requestFullMetadata: requestFullMetadata,
            }),
            returnValue: _i7.Future<List<_i5.XFile>>.value(<_i5.XFile>[]),
          )
          as _i7.Future<List<_i5.XFile>>);

  @override
  _i7.Future<_i5.XFile?> pickMedia({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickMedia, [], {
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
              #imageQuality: imageQuality,
              #requestFullMetadata: requestFullMetadata,
            }),
            returnValue: _i7.Future<_i5.XFile?>.value(),
          )
          as _i7.Future<_i5.XFile?>);

  @override
  _i7.Future<List<_i5.XFile>> pickMultipleMedia({
    double? maxWidth,
    double? maxHeight,
    int? imageQuality,
    int? limit,
    bool? requestFullMetadata = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickMultipleMedia, [], {
              #maxWidth: maxWidth,
              #maxHeight: maxHeight,
              #imageQuality: imageQuality,
              #limit: limit,
              #requestFullMetadata: requestFullMetadata,
            }),
            returnValue: _i7.Future<List<_i5.XFile>>.value(<_i5.XFile>[]),
          )
          as _i7.Future<List<_i5.XFile>>);

  @override
  _i7.Future<_i5.XFile?> pickVideo({
    required _i5.ImageSource? source,
    _i5.CameraDevice? preferredCameraDevice = _i5.CameraDevice.rear,
    Duration? maxDuration,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickVideo, [], {
              #source: source,
              #preferredCameraDevice: preferredCameraDevice,
              #maxDuration: maxDuration,
            }),
            returnValue: _i7.Future<_i5.XFile?>.value(),
          )
          as _i7.Future<_i5.XFile?>);

  @override
  _i7.Future<List<_i5.XFile>> pickMultiVideo({
    Duration? maxDuration,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#pickMultiVideo, [], {
              #maxDuration: maxDuration,
              #limit: limit,
            }),
            returnValue: _i7.Future<List<_i5.XFile>>.value(<_i5.XFile>[]),
          )
          as _i7.Future<List<_i5.XFile>>);

  @override
  _i7.Future<_i5.LostDataResponse> retrieveLostData() =>
      (super.noSuchMethod(
            Invocation.method(#retrieveLostData, []),
            returnValue: _i7.Future<_i5.LostDataResponse>.value(
              _FakeLostDataResponse_15(
                this,
                Invocation.method(#retrieveLostData, []),
              ),
            ),
          )
          as _i7.Future<_i5.LostDataResponse>);

  @override
  bool supportsImageSource(_i5.ImageSource? source) =>
      (super.noSuchMethod(
            Invocation.method(#supportsImageSource, [source]),
            returnValue: false,
          )
          as bool);
}
