// Mocks generated by Mockito 5.4.6 from annotations
// in travel_crew/test/features/trips/presentation/trip_edit_e2e_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:travel_crew/features/trips/domain/repositories/trip_repository.dart'
    as _i3;
import 'package:travel_crew/shared/models/trip_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTripModel_0 extends _i1.SmartFake implements _i2.TripModel {
  _FakeTripModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTripWithMembers_1 extends _i1.SmartFake
    implements _i2.TripWithMembers {
  _FakeTripWithMembers_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTripMemberModel_2 extends _i1.SmartFake
    implements _i2.TripMemberModel {
  _FakeTripMemberModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [TripRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTripRepository extends _i1.Mock implements _i3.TripRepository {
  MockTripRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.TripModel> createTrip({
    required String? name,
    String? description,
    String? destination,
    DateTime? startDate,
    DateTime? endDate,
    String? coverImageUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createTrip, [], {
              #name: name,
              #description: description,
              #destination: destination,
              #startDate: startDate,
              #endDate: endDate,
              #coverImageUrl: coverImageUrl,
            }),
            returnValue: _i4.Future<_i2.TripModel>.value(
              _FakeTripModel_0(
                this,
                Invocation.method(#createTrip, [], {
                  #name: name,
                  #description: description,
                  #destination: destination,
                  #startDate: startDate,
                  #endDate: endDate,
                  #coverImageUrl: coverImageUrl,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.TripModel>);

  @override
  _i4.Future<List<_i2.TripWithMembers>> getUserTrips() =>
      (super.noSuchMethod(
            Invocation.method(#getUserTrips, []),
            returnValue: _i4.Future<List<_i2.TripWithMembers>>.value(
              <_i2.TripWithMembers>[],
            ),
          )
          as _i4.Future<List<_i2.TripWithMembers>>);

  @override
  _i4.Future<_i2.TripWithMembers> getTripById(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#getTripById, [tripId]),
            returnValue: _i4.Future<_i2.TripWithMembers>.value(
              _FakeTripWithMembers_1(
                this,
                Invocation.method(#getTripById, [tripId]),
              ),
            ),
          )
          as _i4.Future<_i2.TripWithMembers>);

  @override
  _i4.Future<_i2.TripModel> updateTrip({
    required String? tripId,
    String? name,
    String? description,
    String? destination,
    DateTime? startDate,
    DateTime? endDate,
    String? coverImageUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateTrip, [], {
              #tripId: tripId,
              #name: name,
              #description: description,
              #destination: destination,
              #startDate: startDate,
              #endDate: endDate,
              #coverImageUrl: coverImageUrl,
            }),
            returnValue: _i4.Future<_i2.TripModel>.value(
              _FakeTripModel_0(
                this,
                Invocation.method(#updateTrip, [], {
                  #tripId: tripId,
                  #name: name,
                  #description: description,
                  #destination: destination,
                  #startDate: startDate,
                  #endDate: endDate,
                  #coverImageUrl: coverImageUrl,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.TripModel>);

  @override
  _i4.Future<void> deleteTrip(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTrip, [tripId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.TripMemberModel>> getTripMembers(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#getTripMembers, [tripId]),
            returnValue: _i4.Future<List<_i2.TripMemberModel>>.value(
              <_i2.TripMemberModel>[],
            ),
          )
          as _i4.Future<List<_i2.TripMemberModel>>);

  @override
  _i4.Future<_i2.TripMemberModel> addMember({
    required String? tripId,
    required String? userId,
    String? role,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addMember, [], {
              #tripId: tripId,
              #userId: userId,
              #role: role,
            }),
            returnValue: _i4.Future<_i2.TripMemberModel>.value(
              _FakeTripMemberModel_2(
                this,
                Invocation.method(#addMember, [], {
                  #tripId: tripId,
                  #userId: userId,
                  #role: role,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.TripMemberModel>);

  @override
  _i4.Future<void> removeMember({
    required String? tripId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeMember, [], {
              #tripId: tripId,
              #userId: userId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<_i2.TripWithMembers> watchTrip(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#watchTrip, [tripId]),
            returnValue: _i4.Stream<_i2.TripWithMembers>.empty(),
          )
          as _i4.Stream<_i2.TripWithMembers>);
}
