// Mocks generated by Mockito 5.4.6 from annotations
// in travel_crew/test/features/expenses/domain/usecases/create_expense_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:travel_crew/features/expenses/domain/repositories/expense_repository.dart'
    as _i3;
import 'package:travel_crew/shared/models/expense_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeExpenseWithSplits_0 extends _i1.SmartFake
    implements _i2.ExpenseWithSplits {
  _FakeExpenseWithSplits_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeExpenseModel_1 extends _i1.SmartFake implements _i2.ExpenseModel {
  _FakeExpenseModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSettlementModel_2 extends _i1.SmartFake
    implements _i2.SettlementModel {
  _FakeSettlementModel_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ExpenseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockExpenseRepository extends _i1.Mock implements _i3.ExpenseRepository {
  MockExpenseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.ExpenseWithSplits>> getUserExpenses() =>
      (super.noSuchMethod(
            Invocation.method(#getUserExpenses, []),
            returnValue: _i4.Future<List<_i2.ExpenseWithSplits>>.value(
              <_i2.ExpenseWithSplits>[],
            ),
          )
          as _i4.Future<List<_i2.ExpenseWithSplits>>);

  @override
  _i4.Future<List<_i2.ExpenseWithSplits>> getTripExpenses(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#getTripExpenses, [tripId]),
            returnValue: _i4.Future<List<_i2.ExpenseWithSplits>>.value(
              <_i2.ExpenseWithSplits>[],
            ),
          )
          as _i4.Future<List<_i2.ExpenseWithSplits>>);

  @override
  _i4.Future<List<_i2.ExpenseWithSplits>> getStandaloneExpenses() =>
      (super.noSuchMethod(
            Invocation.method(#getStandaloneExpenses, []),
            returnValue: _i4.Future<List<_i2.ExpenseWithSplits>>.value(
              <_i2.ExpenseWithSplits>[],
            ),
          )
          as _i4.Future<List<_i2.ExpenseWithSplits>>);

  @override
  _i4.Future<_i2.ExpenseWithSplits> getExpenseById(String? expenseId) =>
      (super.noSuchMethod(
            Invocation.method(#getExpenseById, [expenseId]),
            returnValue: _i4.Future<_i2.ExpenseWithSplits>.value(
              _FakeExpenseWithSplits_0(
                this,
                Invocation.method(#getExpenseById, [expenseId]),
              ),
            ),
          )
          as _i4.Future<_i2.ExpenseWithSplits>);

  @override
  _i4.Future<_i2.ExpenseModel> createExpense({
    String? tripId,
    required String? title,
    String? description,
    required double? amount,
    String? category,
    required String? paidBy,
    required List<String>? splitWith,
    String? splitType = 'equal',
    DateTime? transactionDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createExpense, [], {
              #tripId: tripId,
              #title: title,
              #description: description,
              #amount: amount,
              #category: category,
              #paidBy: paidBy,
              #splitWith: splitWith,
              #splitType: splitType,
              #transactionDate: transactionDate,
            }),
            returnValue: _i4.Future<_i2.ExpenseModel>.value(
              _FakeExpenseModel_1(
                this,
                Invocation.method(#createExpense, [], {
                  #tripId: tripId,
                  #title: title,
                  #description: description,
                  #amount: amount,
                  #category: category,
                  #paidBy: paidBy,
                  #splitWith: splitWith,
                  #splitType: splitType,
                  #transactionDate: transactionDate,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ExpenseModel>);

  @override
  _i4.Future<_i2.ExpenseModel> updateExpense({
    required String? expenseId,
    String? title,
    String? description,
    double? amount,
    String? category,
    DateTime? transactionDate,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateExpense, [], {
              #expenseId: expenseId,
              #title: title,
              #description: description,
              #amount: amount,
              #category: category,
              #transactionDate: transactionDate,
            }),
            returnValue: _i4.Future<_i2.ExpenseModel>.value(
              _FakeExpenseModel_1(
                this,
                Invocation.method(#updateExpense, [], {
                  #expenseId: expenseId,
                  #title: title,
                  #description: description,
                  #amount: amount,
                  #category: category,
                  #transactionDate: transactionDate,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ExpenseModel>);

  @override
  _i4.Future<void> deleteExpense(String? expenseId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteExpense, [expenseId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.BalanceSummary>> getBalances({
    String? tripId,
    String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getBalances, [], {
              #tripId: tripId,
              #userId: userId,
            }),
            returnValue: _i4.Future<List<_i2.BalanceSummary>>.value(
              <_i2.BalanceSummary>[],
            ),
          )
          as _i4.Future<List<_i2.BalanceSummary>>);

  @override
  _i4.Future<_i2.SettlementModel> createSettlement({
    String? tripId,
    required String? fromUser,
    required String? toUser,
    required double? amount,
    String? paymentMethod,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createSettlement, [], {
              #tripId: tripId,
              #fromUser: fromUser,
              #toUser: toUser,
              #amount: amount,
              #paymentMethod: paymentMethod,
            }),
            returnValue: _i4.Future<_i2.SettlementModel>.value(
              _FakeSettlementModel_2(
                this,
                Invocation.method(#createSettlement, [], {
                  #tripId: tripId,
                  #fromUser: fromUser,
                  #toUser: toUser,
                  #amount: amount,
                  #paymentMethod: paymentMethod,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.SettlementModel>);

  @override
  _i4.Future<List<_i2.SettlementModel>> getSettlements({
    String? tripId,
    String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getSettlements, [], {
              #tripId: tripId,
              #userId: userId,
            }),
            returnValue: _i4.Future<List<_i2.SettlementModel>>.value(
              <_i2.SettlementModel>[],
            ),
          )
          as _i4.Future<List<_i2.SettlementModel>>);

  @override
  _i4.Future<_i2.SettlementModel> updateSettlementStatus({
    required String? settlementId,
    required String? status,
    String? paymentProofUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateSettlementStatus, [], {
              #settlementId: settlementId,
              #status: status,
              #paymentProofUrl: paymentProofUrl,
            }),
            returnValue: _i4.Future<_i2.SettlementModel>.value(
              _FakeSettlementModel_2(
                this,
                Invocation.method(#updateSettlementStatus, [], {
                  #settlementId: settlementId,
                  #status: status,
                  #paymentProofUrl: paymentProofUrl,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.SettlementModel>);
}
