import 'package:flutter/foundation.dart';
import '../../../../core/config/data_source_config.dart';
import '../../../../shared/models/trip_model.dart';
import '../../domain/repositories/trip_repository.dart';
import '../datasources/trip_remote_datasource.dart';
import '../datasources/trip_local_datasource.dart';

/// Implementation of trip repository with hybrid Supabase/SQLite support
///
/// Uses Supabase as primary data source with SQLite as fallback/offline storage.
/// Configurable via DataSourceConfig.
class TripRepositoryImpl implements TripRepository {
  final TripRemoteDataSource _remoteDataSource;
  final TripLocalDataSource _localDataSource;

  TripRepositoryImpl(this._remoteDataSource, this._localDataSource);

  @override
  Future<TripModel> createTrip({
    required String name,
    String? description,
    String? destination,
    DateTime? startDate,
    DateTime? endDate,
    String? coverImageUrl,
  }) async {
    try {
      // Create trip model
      final trip = TripModel(
        id: '', // Will be generated by backend
        name: name,
        description: description,
        destination: destination,
        startDate: startDate,
        endDate: endDate,
        coverImageUrl: coverImageUrl,
        createdBy: '', // Will be set by backend
      );

      // Use Supabase if configured as primary
      if (DataSourceConfig.useSupabase) {
        try {
          final createdTrip = await _remoteDataSource.createTrip(trip);

          // Sync to SQLite if enabled
          if (DataSourceConfig.enableSync) {
            try {
              await _localDataSource.createTrip(
                name: createdTrip.name,
                description: createdTrip.description,
                destination: createdTrip.destination,
                startDate: createdTrip.startDate,
                endDate: createdTrip.endDate,
                coverImageUrl: createdTrip.coverImageUrl,
              );
            } catch (e) {
              if (kDebugMode) print('⚠️  Failed to sync to SQLite: $e');
            }
          }

          return createdTrip;
        } catch (e) {
          if (kDebugMode) print('❌ Supabase create failed: $e');

          // Fallback to SQLite if enabled
          if (DataSourceConfig.enableFallback) {
            if (kDebugMode) print('⚠️  Using SQLite fallback');
            return await _localDataSource.createTrip(
              name: name,
              description: description,
              destination: destination,
              startDate: startDate,
              endDate: endDate,
              coverImageUrl: coverImageUrl,
            );
          }
          rethrow;
        }
      } else {
        // Use SQLite as primary
        return await _localDataSource.createTrip(
          name: name,
          description: description,
          destination: destination,
          startDate: startDate,
          endDate: endDate,
          coverImageUrl: coverImageUrl,
        );
      }
    } catch (e) {
      throw Exception('Failed to create trip: $e');
    }
  }

  @override
  Future<List<TripWithMembers>> getUserTrips() async {
    try {
      // Use Supabase if configured as primary
      if (DataSourceConfig.useSupabase) {
        try {
          final trips = await _remoteDataSource.getUserTrips();

          // Sync to SQLite if enabled
          if (DataSourceConfig.enableSync && trips.isNotEmpty) {
            try {
              // TODO: Implement sync logic
              if (kDebugMode) print('✓ Fetched ${trips.length} trips from Supabase');
            } catch (e) {
              if (kDebugMode) print('⚠️  Failed to sync to SQLite: $e');
            }
          }

          return trips;
        } catch (e) {
          if (kDebugMode) print('❌ Supabase fetch failed: $e');

          // Fallback to SQLite if enabled
          if (DataSourceConfig.enableFallback) {
            if (kDebugMode) print('⚠️  Using SQLite fallback');
            return await _localDataSource.getUserTrips();
          }
          rethrow;
        }
      } else {
        // Use SQLite as primary
        return await _localDataSource.getUserTrips();
      }
    } catch (e) {
      throw Exception('Failed to get user trips: $e');
    }
  }

  @override
  Future<TripWithMembers> getTripById(String tripId) async {
    try {
      // Use Supabase if configured as primary
      if (DataSourceConfig.useSupabase) {
        try {
          final trip = await _remoteDataSource.getTripById(tripId);
          if (trip == null) {
            throw Exception('Trip not found');
          }
          return trip;
        } catch (e) {
          if (kDebugMode) print('❌ Supabase fetch failed: $e');

          // Fallback to SQLite if enabled
          if (DataSourceConfig.enableFallback) {
            if (kDebugMode) print('⚠️  Using SQLite fallback');
            return await _localDataSource.getTripById(tripId);
          }
          rethrow;
        }
      } else {
        // Use SQLite as primary
        return await _localDataSource.getTripById(tripId);
      }
    } catch (e) {
      throw Exception('Failed to get trip: $e');
    }
  }

  @override
  Future<TripModel> updateTrip({
    required String tripId,
    String? name,
    String? description,
    String? destination,
    DateTime? startDate,
    DateTime? endDate,
    String? coverImageUrl,
  }) async {
    try {
      // Build updates map
      final updates = <String, dynamic>{};
      if (name != null) updates['name'] = name;
      if (description != null) updates['description'] = description;
      if (destination != null) updates['destination'] = destination;
      if (startDate != null) updates['startDate'] = startDate;
      if (endDate != null) updates['endDate'] = endDate;
      if (coverImageUrl != null) updates['coverImageUrl'] = coverImageUrl;

      // Use Supabase if configured as primary
      if (DataSourceConfig.useSupabase) {
        try {
          await _remoteDataSource.updateTrip(tripId, updates);

          // Sync to SQLite if enabled
          if (DataSourceConfig.enableSync) {
            try {
              await _localDataSource.updateTrip(
                tripId: tripId,
                name: name,
                description: description,
                destination: destination,
                startDate: startDate,
                endDate: endDate,
                coverImageUrl: coverImageUrl,
              );
            } catch (e) {
              if (kDebugMode) print('⚠️  Failed to sync to SQLite: $e');
            }
          }

          // Fetch and return updated trip
          final updatedTrip = await _remoteDataSource.getTripById(tripId);
          if (updatedTrip == null) {
            throw Exception('Failed to fetch updated trip');
          }
          return updatedTrip.trip;
        } catch (e) {
          if (kDebugMode) print('❌ Supabase update failed: $e');

          // Fallback to SQLite if enabled
          if (DataSourceConfig.enableFallback) {
            if (kDebugMode) print('⚠️  Using SQLite fallback');
            return await _localDataSource.updateTrip(
              tripId: tripId,
              name: name,
              description: description,
              destination: destination,
              startDate: startDate,
              endDate: endDate,
              coverImageUrl: coverImageUrl,
            );
          }
          rethrow;
        }
      } else {
        // Use SQLite as primary
        return await _localDataSource.updateTrip(
          tripId: tripId,
          name: name,
          description: description,
          destination: destination,
          startDate: startDate,
          endDate: endDate,
          coverImageUrl: coverImageUrl,
        );
      }
    } catch (e) {
      throw Exception('Failed to update trip: $e');
    }
  }

  @override
  Future<void> deleteTrip(String tripId) async {
    try {
      // Use Supabase if configured as primary
      if (DataSourceConfig.useSupabase) {
        try {
          await _remoteDataSource.deleteTrip(tripId);

          // Sync to SQLite if enabled
          if (DataSourceConfig.enableSync) {
            try {
              await _localDataSource.deleteTrip(tripId);
            } catch (e) {
              if (kDebugMode) print('⚠️  Failed to sync to SQLite: $e');
            }
          }
        } catch (e) {
          if (kDebugMode) print('❌ Supabase delete failed: $e');

          // Fallback to SQLite if enabled
          if (DataSourceConfig.enableFallback) {
            if (kDebugMode) print('⚠️  Using SQLite fallback');
            await _localDataSource.deleteTrip(tripId);
            return;
          }
          rethrow;
        }
      } else {
        // Use SQLite as primary
        await _localDataSource.deleteTrip(tripId);
      }
    } catch (e) {
      throw Exception('Failed to delete trip: $e');
    }
  }

  @override
  Future<List<TripMemberModel>> getTripMembers(String tripId) async {
    try {
      // Use Supabase if configured as primary
      if (DataSourceConfig.useSupabase) {
        try {
          final trip = await _remoteDataSource.getTripById(tripId);
          if (trip == null) {
            throw Exception('Trip not found');
          }
          return trip.members;
        } catch (e) {
          if (kDebugMode) print('❌ Supabase fetch failed: $e');

          // Fallback to SQLite if enabled
          if (DataSourceConfig.enableFallback) {
            if (kDebugMode) print('⚠️  Using SQLite fallback');
            return await _localDataSource.getTripMembers(tripId);
          }
          rethrow;
        }
      } else {
        // Use SQLite as primary
        return await _localDataSource.getTripMembers(tripId);
      }
    } catch (e) {
      throw Exception('Failed to get trip members: $e');
    }
  }

  @override
  Future<TripMemberModel> addMember({
    required String tripId,
    required String userId,
    String role = 'member',
  }) async {
    try {
      // Use Supabase if configured as primary
      if (DataSourceConfig.useSupabase) {
        try {
          await _remoteDataSource.addMember(tripId, userId, role: role);

          // Sync to SQLite if enabled
          if (DataSourceConfig.enableSync) {
            try {
              await _localDataSource.addMember(
                tripId: tripId,
                userId: userId,
                role: role,
              );
            } catch (e) {
              if (kDebugMode) print('⚠️  Failed to sync to SQLite: $e');
            }
          }

          // Return the member (fetch from trip)
          final trip = await _remoteDataSource.getTripById(tripId);
          final member = trip?.members.firstWhere(
            (m) => m.userId == userId,
            orElse: () => throw Exception('Member not found after adding'),
          );
          if (member == null) throw Exception('Member not found');
          return member;
        } catch (e) {
          if (kDebugMode) print('❌ Supabase add member failed: $e');

          // Fallback to SQLite if enabled
          if (DataSourceConfig.enableFallback) {
            if (kDebugMode) print('⚠️  Using SQLite fallback');
            return await _localDataSource.addMember(
              tripId: tripId,
              userId: userId,
              role: role,
            );
          }
          rethrow;
        }
      } else {
        // Use SQLite as primary
        return await _localDataSource.addMember(
          tripId: tripId,
          userId: userId,
          role: role,
        );
      }
    } catch (e) {
      throw Exception('Failed to add member: $e');
    }
  }

  @override
  Future<void> removeMember({
    required String tripId,
    required String userId,
  }) async {
    try {
      // Use Supabase if configured as primary
      if (DataSourceConfig.useSupabase) {
        try {
          await _remoteDataSource.removeMember(tripId, userId);

          // Sync to SQLite if enabled
          if (DataSourceConfig.enableSync) {
            try {
              await _localDataSource.removeMember(tripId: tripId, userId: userId);
            } catch (e) {
              if (kDebugMode) print('⚠️  Failed to sync to SQLite: $e');
            }
          }
        } catch (e) {
          if (kDebugMode) print('❌ Supabase remove member failed: $e');

          // Fallback to SQLite if enabled
          if (DataSourceConfig.enableFallback) {
            if (kDebugMode) print('⚠️  Using SQLite fallback');
            await _localDataSource.removeMember(tripId: tripId, userId: userId);
            return;
          }
          rethrow;
        }
      } else {
        // Use SQLite as primary
        await _localDataSource.removeMember(tripId: tripId, userId: userId);
      }
    } catch (e) {
      throw Exception('Failed to remove member: $e');
    }
  }

  @override
  Stream<TripWithMembers> watchTrip(String tripId) {
    // Use Supabase real-time if configured
    if (DataSourceConfig.useSupabase) {
      // TODO: Implement Supabase real-time watch for single trip
      // For now, fall back to local
      return _localDataSource.watchTrip(tripId);
    } else {
      return _localDataSource.watchTrip(tripId);
    }
  }
}
