import '../../../../shared/models/trip_model.dart';
import '../../domain/repositories/trip_repository.dart';
import '../datasources/trip_remote_datasource.dart';

/// Implementation of trip repository using Supabase as the data source
class TripRepositoryImpl implements TripRepository {
  final TripRemoteDataSource _remoteDataSource;

  TripRepositoryImpl(this._remoteDataSource);

  @override
  Future<TripModel> createTrip({
    required String name,
    String? description,
    String? destination,
    DateTime? startDate,
    DateTime? endDate,
    String? coverImageUrl,
  }) async {
    try {
      final trip = TripModel(
        id: '', // Will be generated by backend
        name: name,
        description: description,
        destination: destination,
        startDate: startDate,
        endDate: endDate,
        coverImageUrl: coverImageUrl,
        createdBy: '', // Will be set by backend
      );

      return await _remoteDataSource.createTrip(trip);
    } catch (e) {
      throw Exception('Failed to create trip: $e');
    }
  }

  @override
  Future<List<TripWithMembers>> getUserTrips() async {
    try {
      return await _remoteDataSource.getUserTrips();
    } catch (e) {
      throw Exception('Failed to get user trips: $e');
    }
  }

  @override
  Future<TripWithMembers> getTripById(String tripId) async {
    try {
      final trip = await _remoteDataSource.getTripById(tripId);
      if (trip == null) {
        throw Exception('Trip not found');
      }
      return trip;
    } catch (e) {
      throw Exception('Failed to get trip: $e');
    }
  }

  @override
  Future<TripModel> updateTrip({
    required String tripId,
    String? name,
    String? description,
    String? destination,
    DateTime? startDate,
    DateTime? endDate,
    String? coverImageUrl,
  }) async {
    try {
      // Build updates map
      final updates = <String, dynamic>{};
      if (name != null) updates['name'] = name;
      if (description != null) updates['description'] = description;
      if (destination != null) updates['destination'] = destination;
      if (startDate != null) updates['startDate'] = startDate;
      if (endDate != null) updates['endDate'] = endDate;
      if (coverImageUrl != null) updates['coverImageUrl'] = coverImageUrl;

      await _remoteDataSource.updateTrip(tripId, updates);

      // Fetch and return updated trip
      final updatedTrip = await _remoteDataSource.getTripById(tripId);
      if (updatedTrip == null) {
        throw Exception('Failed to fetch updated trip');
      }
      return updatedTrip.trip;
    } catch (e) {
      throw Exception('Failed to update trip: $e');
    }
  }

  @override
  Future<void> deleteTrip(String tripId) async {
    try {
      await _remoteDataSource.deleteTrip(tripId);
    } catch (e) {
      throw Exception('Failed to delete trip: $e');
    }
  }

  @override
  Future<List<TripMemberModel>> getTripMembers(String tripId) async {
    try {
      final trip = await _remoteDataSource.getTripById(tripId);
      if (trip == null) {
        throw Exception('Trip not found');
      }
      return trip.members;
    } catch (e) {
      throw Exception('Failed to get trip members: $e');
    }
  }

  @override
  Future<TripMemberModel> addMember({
    required String tripId,
    required String userId,
    String role = 'member',
  }) async {
    try {
      await _remoteDataSource.addMember(tripId, userId, role: role);

      // Fetch and return the added member
      final trip = await _remoteDataSource.getTripById(tripId);
      final member = trip?.members.firstWhere(
        (m) => m.userId == userId,
        orElse: () => throw Exception('Member not found after adding'),
      );
      if (member == null) throw Exception('Member not found');
      return member;
    } catch (e) {
      throw Exception('Failed to add member: $e');
    }
  }

  @override
  Future<void> removeMember({
    required String tripId,
    required String userId,
  }) async {
    try {
      await _remoteDataSource.removeMember(tripId, userId);
    } catch (e) {
      throw Exception('Failed to remove member: $e');
    }
  }

  @override
  Stream<List<TripWithMembers>> watchUserTrips() {
    try {
      // Delegate to remote datasource which has real-time implementation
      return _remoteDataSource.watchUserTrips();
    } catch (e) {
      throw Exception('Failed to watch user trips: $e');
    }
  }

  @override
  Stream<TripWithMembers> watchTrip(String tripId) {
    try {
      // Delegate to remote datasource which has real-time implementation
      return _remoteDataSource.watchTrip(tripId);
    } catch (e) {
      throw Exception('Failed to watch trip: $e');
    }
  }
}
