// Mocks generated by Mockito 5.4.6 from annotations
// in travel_crew/test/features/messaging/performance/messaging_performance_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:connectivity_plus/connectivity_plus.dart' as _i6;
import 'package:connectivity_plus_platform_interface/connectivity_plus_platform_interface.dart'
    as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:travel_crew/features/messaging/data/datasources/message_local_datasource.dart'
    as _i3;
import 'package:travel_crew/features/messaging/data/datasources/message_remote_datasource.dart'
    as _i5;
import 'package:travel_crew/shared/models/message_model.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMessageModel_0 extends _i1.SmartFake implements _i2.MessageModel {
  _FakeMessageModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MessageLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageLocalDataSource extends _i1.Mock
    implements _i3.MessageLocalDataSource {
  MockMessageLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveMessage(_i2.MessageModel? message) =>
      (super.noSuchMethod(
            Invocation.method(#saveMessage, [message]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveMessages(List<_i2.MessageModel>? messages) =>
      (super.noSuchMethod(
            Invocation.method(#saveMessages, [messages]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.MessageModel>> getTripMessages({
    required String? tripId,
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTripMessages, [], {
              #tripId: tripId,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i4.Future<List<_i2.MessageModel>>.value(
              <_i2.MessageModel>[],
            ),
          )
          as _i4.Future<List<_i2.MessageModel>>);

  @override
  _i4.Future<_i2.MessageModel?> getMessageById(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageById, [messageId]),
            returnValue: _i4.Future<_i2.MessageModel?>.value(),
          )
          as _i4.Future<_i2.MessageModel?>);

  @override
  _i4.Future<List<_i2.MessageModel>> getMessagesAfter({
    required String? tripId,
    required DateTime? timestamp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesAfter, [], {
              #tripId: tripId,
              #timestamp: timestamp,
            }),
            returnValue: _i4.Future<List<_i2.MessageModel>>.value(
              <_i2.MessageModel>[],
            ),
          )
          as _i4.Future<List<_i2.MessageModel>>);

  @override
  _i4.Future<List<_i2.MessageModel>> getThreadedReplies(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#getThreadedReplies, [messageId]),
            returnValue: _i4.Future<List<_i2.MessageModel>>.value(
              <_i2.MessageModel>[],
            ),
          )
          as _i4.Future<List<_i2.MessageModel>>);

  @override
  _i4.Future<void> deleteMessage(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [messageId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> markMessageAsRead({
    required String? messageId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#markMessageAsRead, [], {
              #messageId: messageId,
              #userId: userId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> getUnreadCount({
    required String? tripId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadCount, [], {
              #tripId: tripId,
              #userId: userId,
            }),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> addReaction({
    required String? messageId,
    required String? userId,
    required String? emoji,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addReaction, [], {
              #messageId: messageId,
              #userId: userId,
              #emoji: emoji,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeReaction({
    required String? messageId,
    required String? userId,
    required String? emoji,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeReaction, [], {
              #messageId: messageId,
              #userId: userId,
              #emoji: emoji,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> queueMessage(_i2.QueuedMessageModel? queuedMessage) =>
      (super.noSuchMethod(
            Invocation.method(#queueMessage, [queuedMessage]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.QueuedMessageModel>> getPendingMessages() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingMessages, []),
            returnValue: _i4.Future<List<_i2.QueuedMessageModel>>.value(
              <_i2.QueuedMessageModel>[],
            ),
          )
          as _i4.Future<List<_i2.QueuedMessageModel>>);

  @override
  _i4.Future<List<_i2.QueuedMessageModel>> getPendingMessagesByTrip(
    String? tripId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPendingMessagesByTrip, [tripId]),
            returnValue: _i4.Future<List<_i2.QueuedMessageModel>>.value(
              <_i2.QueuedMessageModel>[],
            ),
          )
          as _i4.Future<List<_i2.QueuedMessageModel>>);

  @override
  _i4.Future<void> updateQueueStatus({
    required String? queueId,
    required String? status,
    String? errorMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateQueueStatus, [], {
              #queueId: queueId,
              #status: status,
              #errorMessage: errorMessage,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeFromQueue(String? queueId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromQueue, [queueId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearTripCache(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#clearTripCache, [tripId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllCache, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> getCacheSize() =>
      (super.noSuchMethod(
            Invocation.method(#getCacheSize, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<DateTime?> getLastMessageTimestamp(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#getLastMessageTimestamp, [tripId]),
            returnValue: _i4.Future<DateTime?>.value(),
          )
          as _i4.Future<DateTime?>);

  @override
  _i4.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [MessageRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageRemoteDataSource extends _i1.Mock
    implements _i5.MessageRemoteDataSource {
  MockMessageRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.MessageModel> sendMessage(_i2.MessageModel? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [message]),
            returnValue: _i4.Future<_i2.MessageModel>.value(
              _FakeMessageModel_0(
                this,
                Invocation.method(#sendMessage, [message]),
              ),
            ),
          )
          as _i4.Future<_i2.MessageModel>);

  @override
  _i4.Future<List<_i2.MessageModel>> getTripMessages({
    required String? tripId,
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTripMessages, [], {
              #tripId: tripId,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i4.Future<List<_i2.MessageModel>>.value(
              <_i2.MessageModel>[],
            ),
          )
          as _i4.Future<List<_i2.MessageModel>>);

  @override
  _i4.Future<_i2.MessageModel?> getMessageById(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageById, [messageId]),
            returnValue: _i4.Future<_i2.MessageModel?>.value(),
          )
          as _i4.Future<_i2.MessageModel?>);

  @override
  _i4.Future<List<_i2.MessageModel>> getMessagesAfter({
    required String? tripId,
    required DateTime? timestamp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesAfter, [], {
              #tripId: tripId,
              #timestamp: timestamp,
            }),
            returnValue: _i4.Future<List<_i2.MessageModel>>.value(
              <_i2.MessageModel>[],
            ),
          )
          as _i4.Future<List<_i2.MessageModel>>);

  @override
  _i4.Future<List<_i2.MessageModel>> getThreadedReplies(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#getThreadedReplies, [messageId]),
            returnValue: _i4.Future<List<_i2.MessageModel>>.value(
              <_i2.MessageModel>[],
            ),
          )
          as _i4.Future<List<_i2.MessageModel>>);

  @override
  _i4.Future<void> deleteMessage(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [messageId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> markMessageAsRead({
    required String? messageId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#markMessageAsRead, [], {
              #messageId: messageId,
              #userId: userId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> addReaction({
    required String? messageId,
    required String? userId,
    required String? emoji,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addReaction, [], {
              #messageId: messageId,
              #userId: userId,
              #emoji: emoji,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeReaction({
    required String? messageId,
    required String? userId,
    required String? emoji,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeReaction, [], {
              #messageId: messageId,
              #userId: userId,
              #emoji: emoji,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<_i2.MessageModel> subscribeToTripMessages(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToTripMessages, [tripId]),
            returnValue: _i4.Stream<_i2.MessageModel>.empty(),
          )
          as _i4.Stream<_i2.MessageModel>);

  @override
  _i4.Stream<_i2.MessageModel> subscribeToMessageUpdates(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToMessageUpdates, [messageId]),
            returnValue: _i4.Stream<_i2.MessageModel>.empty(),
          )
          as _i4.Stream<_i2.MessageModel>);

  @override
  _i4.Future<void> queueMessage(_i2.QueuedMessageModel? queuedMessage) =>
      (super.noSuchMethod(
            Invocation.method(#queueMessage, [queuedMessage]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.QueuedMessageModel>> getPendingMessages() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingMessages, []),
            returnValue: _i4.Future<List<_i2.QueuedMessageModel>>.value(
              <_i2.QueuedMessageModel>[],
            ),
          )
          as _i4.Future<List<_i2.QueuedMessageModel>>);

  @override
  _i4.Future<void> updateQueueStatus({
    required String? queueId,
    required String? status,
    String? errorMessage,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateQueueStatus, [], {
              #queueId: queueId,
              #status: status,
              #errorMessage: errorMessage,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeFromQueue(String? queueId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromQueue, [queueId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [Connectivity].
///
/// See the documentation for Mockito's code generation for more information.
class MockConnectivity extends _i1.Mock implements _i6.Connectivity {
  MockConnectivity() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<List<_i7.ConnectivityResult>> get onConnectivityChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onConnectivityChanged),
            returnValue: _i4.Stream<List<_i7.ConnectivityResult>>.empty(),
          )
          as _i4.Stream<List<_i7.ConnectivityResult>>);

  @override
  _i4.Future<List<_i7.ConnectivityResult>> checkConnectivity() =>
      (super.noSuchMethod(
            Invocation.method(#checkConnectivity, []),
            returnValue: _i4.Future<List<_i7.ConnectivityResult>>.value(
              <_i7.ConnectivityResult>[],
            ),
          )
          as _i4.Future<List<_i7.ConnectivityResult>>);
}
