// Mocks generated by Mockito 5.4.6 from annotations
// in travel_crew/test/features/messaging/domain/usecases/get_unread_count_usecase_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:travel_crew/features/messaging/domain/entities/message_entity.dart'
    as _i2;
import 'package:travel_crew/features/messaging/domain/repositories/message_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeMessageEntity_0 extends _i1.SmartFake implements _i2.MessageEntity {
  _FakeMessageEntity_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MessageRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMessageRepository extends _i1.Mock implements _i3.MessageRepository {
  MockMessageRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.MessageEntity> sendMessage({
    required String? tripId,
    required String? senderId,
    required String? message,
    required _i2.MessageType? messageType,
    String? replyToId,
    String? attachmentUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #tripId: tripId,
              #senderId: senderId,
              #message: message,
              #messageType: messageType,
              #replyToId: replyToId,
              #attachmentUrl: attachmentUrl,
            }),
            returnValue: _i4.Future<_i2.MessageEntity>.value(
              _FakeMessageEntity_0(
                this,
                Invocation.method(#sendMessage, [], {
                  #tripId: tripId,
                  #senderId: senderId,
                  #message: message,
                  #messageType: messageType,
                  #replyToId: replyToId,
                  #attachmentUrl: attachmentUrl,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.MessageEntity>);

  @override
  _i4.Future<List<_i2.MessageEntity>> getTripMessages({
    required String? tripId,
    int? limit = 50,
    int? offset = 0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getTripMessages, [], {
              #tripId: tripId,
              #limit: limit,
              #offset: offset,
            }),
            returnValue: _i4.Future<List<_i2.MessageEntity>>.value(
              <_i2.MessageEntity>[],
            ),
          )
          as _i4.Future<List<_i2.MessageEntity>>);

  @override
  _i4.Future<_i2.MessageEntity?> getMessageById(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#getMessageById, [messageId]),
            returnValue: _i4.Future<_i2.MessageEntity?>.value(),
          )
          as _i4.Future<_i2.MessageEntity?>);

  @override
  _i4.Future<List<_i2.MessageEntity>> getMessagesAfter({
    required String? tripId,
    required DateTime? timestamp,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getMessagesAfter, [], {
              #tripId: tripId,
              #timestamp: timestamp,
            }),
            returnValue: _i4.Future<List<_i2.MessageEntity>>.value(
              <_i2.MessageEntity>[],
            ),
          )
          as _i4.Future<List<_i2.MessageEntity>>);

  @override
  _i4.Future<List<_i2.MessageEntity>> getThreadedReplies(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#getThreadedReplies, [messageId]),
            returnValue: _i4.Future<List<_i2.MessageEntity>>.value(
              <_i2.MessageEntity>[],
            ),
          )
          as _i4.Future<List<_i2.MessageEntity>>);

  @override
  _i4.Future<void> deleteMessage(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [messageId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> markMessageAsRead({
    required String? messageId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#markMessageAsRead, [], {
              #messageId: messageId,
              #userId: userId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> markAllMessagesAsRead({
    required String? tripId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#markAllMessagesAsRead, [], {
              #tripId: tripId,
              #userId: userId,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> getUnreadCount({
    required String? tripId,
    required String? userId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getUnreadCount, [], {
              #tripId: tripId,
              #userId: userId,
            }),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> addReaction({
    required String? messageId,
    required String? userId,
    required String? emoji,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#addReaction, [], {
              #messageId: messageId,
              #userId: userId,
              #emoji: emoji,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeReaction({
    required String? messageId,
    required String? userId,
    required String? emoji,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#removeReaction, [], {
              #messageId: messageId,
              #userId: userId,
              #emoji: emoji,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.QueuedMessageEntity>> getPendingMessages() =>
      (super.noSuchMethod(
            Invocation.method(#getPendingMessages, []),
            returnValue: _i4.Future<List<_i2.QueuedMessageEntity>>.value(
              <_i2.QueuedMessageEntity>[],
            ),
          )
          as _i4.Future<List<_i2.QueuedMessageEntity>>);

  @override
  _i4.Future<List<_i2.QueuedMessageEntity>> getPendingMessagesByTrip(
    String? tripId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPendingMessagesByTrip, [tripId]),
            returnValue: _i4.Future<List<_i2.QueuedMessageEntity>>.value(
              <_i2.QueuedMessageEntity>[],
            ),
          )
          as _i4.Future<List<_i2.QueuedMessageEntity>>);

  @override
  _i4.Future<void> retryMessage(String? queuedMessageId) =>
      (super.noSuchMethod(
            Invocation.method(#retryMessage, [queuedMessageId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeFromQueue(String? queuedMessageId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFromQueue, [queuedMessageId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> syncPendingMessages() =>
      (super.noSuchMethod(
            Invocation.method(#syncPendingMessages, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Stream<List<_i2.MessageEntity>> subscribeToTripMessages(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToTripMessages, [tripId]),
            returnValue: _i4.Stream<List<_i2.MessageEntity>>.empty(),
          )
          as _i4.Stream<List<_i2.MessageEntity>>);

  @override
  _i4.Stream<_i2.MessageEntity> subscribeToMessageUpdates(String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToMessageUpdates, [messageId]),
            returnValue: _i4.Stream<_i2.MessageEntity>.empty(),
          )
          as _i4.Stream<_i2.MessageEntity>);

  @override
  _i4.Future<void> clearTripCache(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#clearTripCache, [tripId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> clearAllCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllCache, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<int> getCacheSize() =>
      (super.noSuchMethod(
            Invocation.method(#getCacheSize, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);
}
