// Mocks generated by Mockito 5.4.6 from annotations
// in travel_crew/test/features/trips/e2e/trip_history_e2e_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:travel_crew/features/trips/domain/repositories/trip_repository.dart'
    as _i2;
import 'package:travel_crew/features/trips/domain/usecases/get_trip_history_usecase.dart'
    as _i3;
import 'package:travel_crew/shared/models/trip_model.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTripRepository_0 extends _i1.SmartFake
    implements _i2.TripRepository {
  _FakeTripRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTripHistoryStatistics_1 extends _i1.SmartFake
    implements _i3.TripHistoryStatistics {
  _FakeTripHistoryStatistics_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetTripHistoryUseCase].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetTripHistoryUseCase extends _i1.Mock
    implements _i3.GetTripHistoryUseCase {
  MockGetTripHistoryUseCase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.TripRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeTripRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.TripRepository);

  @override
  _i4.Future<List<_i5.TripWithMembers>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue: _i4.Future<List<_i5.TripWithMembers>>.value(
              <_i5.TripWithMembers>[],
            ),
          )
          as _i4.Future<List<_i5.TripWithMembers>>);

  @override
  _i4.Stream<List<_i5.TripWithMembers>> watchHistory() =>
      (super.noSuchMethod(
            Invocation.method(#watchHistory, []),
            returnValue: _i4.Stream<List<_i5.TripWithMembers>>.empty(),
          )
          as _i4.Stream<List<_i5.TripWithMembers>>);

  @override
  _i4.Future<_i3.TripHistoryStatistics> getStatistics() =>
      (super.noSuchMethod(
            Invocation.method(#getStatistics, []),
            returnValue: _i4.Future<_i3.TripHistoryStatistics>.value(
              _FakeTripHistoryStatistics_1(
                this,
                Invocation.method(#getStatistics, []),
              ),
            ),
          )
          as _i4.Future<_i3.TripHistoryStatistics>);
}
