// Mocks generated by Mockito 5.4.6 from annotations
// in travel_crew/test/features/admin/data/repositories/admin_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:travel_crew/features/admin/data/datasources/admin_remote_datasource.dart'
    as _i4;
import 'package:travel_crew/features/admin/data/models/admin_activity_log_model.dart'
    as _i8;
import 'package:travel_crew/features/admin/data/models/admin_dashboard_stats_model.dart'
    as _i3;
import 'package:travel_crew/features/admin/data/models/admin_user_model.dart'
    as _i2;
import 'package:travel_crew/features/admin/domain/entities/admin_trip.dart'
    as _i9;
import 'package:travel_crew/features/admin/domain/entities/user_role.dart'
    as _i6;
import 'package:travel_crew/features/admin/domain/entities/user_status.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAdminUserModel_0 extends _i1.SmartFake
    implements _i2.AdminUserModel {
  _FakeAdminUserModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdminDashboardStatsModel_1 extends _i1.SmartFake
    implements _i3.AdminDashboardStatsModel {
  _FakeAdminDashboardStatsModel_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AdminRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdminRemoteDataSource extends _i1.Mock
    implements _i4.AdminRemoteDataSource {
  MockAdminRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<bool> isAdmin() =>
      (super.noSuchMethod(
            Invocation.method(#isAdmin, []),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<List<_i2.AdminUserModel>> getAllUsers({
    int? limit = 50,
    int? offset = 0,
    String? search,
    _i6.UserRole? role,
    _i7.UserStatus? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllUsers, [], {
              #limit: limit,
              #offset: offset,
              #search: search,
              #role: role,
              #status: status,
            }),
            returnValue: _i5.Future<List<_i2.AdminUserModel>>.value(
              <_i2.AdminUserModel>[],
            ),
          )
          as _i5.Future<List<_i2.AdminUserModel>>);

  @override
  _i5.Future<_i2.AdminUserModel> getUserById(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [userId]),
            returnValue: _i5.Future<_i2.AdminUserModel>.value(
              _FakeAdminUserModel_0(
                this,
                Invocation.method(#getUserById, [userId]),
              ),
            ),
          )
          as _i5.Future<_i2.AdminUserModel>);

  @override
  _i5.Future<bool> suspendUser(String? userId, String? reason) =>
      (super.noSuchMethod(
            Invocation.method(#suspendUser, [userId, reason]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> activateUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#activateUser, [userId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> updateUserRole(String? userId, _i6.UserRole? newRole) =>
      (super.noSuchMethod(
            Invocation.method(#updateUserRole, [userId, newRole]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i3.AdminDashboardStatsModel> getDashboardStats() =>
      (super.noSuchMethod(
            Invocation.method(#getDashboardStats, []),
            returnValue: _i5.Future<_i3.AdminDashboardStatsModel>.value(
              _FakeAdminDashboardStatsModel_1(
                this,
                Invocation.method(#getDashboardStats, []),
              ),
            ),
          )
          as _i5.Future<_i3.AdminDashboardStatsModel>);

  @override
  _i5.Future<List<_i8.AdminActivityLogModel>> getActivityLogs({
    int? limit = 50,
    int? offset = 0,
    String? adminId,
    String? targetUserId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getActivityLogs, [], {
              #limit: limit,
              #offset: offset,
              #adminId: adminId,
              #targetUserId: targetUserId,
            }),
            returnValue: _i5.Future<List<_i8.AdminActivityLogModel>>.value(
              <_i8.AdminActivityLogModel>[],
            ),
          )
          as _i5.Future<List<_i8.AdminActivityLogModel>>);

  @override
  _i5.Future<_i2.AdminUserModel> updateUserProfile(
    String? userId, {
    String? fullName,
    String? avatarUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateUserProfile,
              [userId],
              {#fullName: fullName, #avatarUrl: avatarUrl},
            ),
            returnValue: _i5.Future<_i2.AdminUserModel>.value(
              _FakeAdminUserModel_0(
                this,
                Invocation.method(
                  #updateUserProfile,
                  [userId],
                  {#fullName: fullName, #avatarUrl: avatarUrl},
                ),
              ),
            ),
          )
          as _i5.Future<_i2.AdminUserModel>);

  @override
  _i5.Future<List<_i9.AdminTripModel>> getAllTrips({
    int? limit = 50,
    int? offset = 0,
    String? search,
    String? status,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getAllTrips, [], {
              #limit: limit,
              #offset: offset,
              #search: search,
              #status: status,
            }),
            returnValue: _i5.Future<List<_i9.AdminTripModel>>.value(
              <_i9.AdminTripModel>[],
            ),
          )
          as _i5.Future<List<_i9.AdminTripModel>>);

  @override
  _i5.Future<bool> deleteTrip(String? tripId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteTrip, [tripId]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> updateTrip(
    String? tripId, {
    String? name,
    String? description,
    String? destination,
    DateTime? startDate,
    DateTime? endDate,
    double? budget,
    String? currency,
    bool? isCompleted,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateTrip,
              [tripId],
              {
                #name: name,
                #description: description,
                #destination: destination,
                #startDate: startDate,
                #endDate: endDate,
                #budget: budget,
                #currency: currency,
                #isCompleted: isCompleted,
              },
            ),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);
}
